// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'cupertino_text_form_field_row_dj.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

CupertinoTextFormFieldRowDj _$CupertinoTextFormFieldRowDjFromJson(
    Map<String, dynamic> json) {
  return CupertinoTextFormFieldRowDj(
    key: json['key'],
    prefix: json['prefix'],
    padding: json['padding'],
    controller: json['controller'],
    initialValue: json['initialValue'],
    focusNode: json['focusNode'],
    decoration: json['decoration'],
    keyboardType: json['keyboardType'],
    textCapitalization: json['textCapitalization'],
    textInputAction: json['textInputAction'],
    style: json['style'],
    strutStyle: json['strutStyle'],
    textAlign: json['textAlign'],
    textAlignVertical: json['textAlignVertical'],
    autofocus: json['autofocus'],
    readOnly: json['readOnly'],
    toolbarOptions: json['toolbarOptions'],
    showCursor: json['showCursor'],
    obscuringCharacter: json['obscuringCharacter'],
    obscureText: json['obscureText'],
    autocorrect: json['autocorrect'],
    smartDashesType: json['smartDashesType'],
    smartQuotesType: json['smartQuotesType'],
    enableSuggestions: json['enableSuggestions'],
    maxLines: json['maxLines'],
    minLines: json['minLines'],
    expands: json['expands'],
    maxLength: json['maxLength'],
    onChanged: json['onChanged'],
    onTap: json['onTap'],
    onEditingComplete: json['onEditingComplete'],
    onFieldSubmitted: json['onFieldSubmitted'],
    onSaved: json['onSaved'],
    validator: json['validator'],
    inputFormatters: json['inputFormatters'],
    enabled: json['enabled'],
    cursorWidth: json['cursorWidth'],
    cursorHeight: json['cursorHeight'],
    cursorColor: json['cursorColor'],
    keyboardAppearance: json['keyboardAppearance'],
    baseWidgetDjType: json['baseWidgetDjType'],
  );
}

Map<String, dynamic> _$CupertinoTextFormFieldRowDjToJson(
        CupertinoTextFormFieldRowDj instance) =>
    <String, dynamic>{
      'baseWidgetDjType': instance.baseWidgetDjType,
      'key': instance.key,
      'prefix': instance.prefix,
      'padding': instance.padding,
      'controller': instance.controller,
      'initialValue': instance.initialValue,
      'focusNode': instance.focusNode,
      'decoration': instance.decoration,
      'keyboardType': instance.keyboardType,
      'textCapitalization': instance.textCapitalization,
      'textInputAction': instance.textInputAction,
      'style': instance.style,
      'strutStyle': instance.strutStyle,
      'textAlign': instance.textAlign,
      'textAlignVertical': instance.textAlignVertical,
      'autofocus': instance.autofocus,
      'readOnly': instance.readOnly,
      'toolbarOptions': instance.toolbarOptions,
      'showCursor': instance.showCursor,
      'obscuringCharacter': instance.obscuringCharacter,
      'obscureText': instance.obscureText,
      'autocorrect': instance.autocorrect,
      'smartDashesType': instance.smartDashesType,
      'smartQuotesType': instance.smartQuotesType,
      'enableSuggestions': instance.enableSuggestions,
      'maxLines': instance.maxLines,
      'minLines': instance.minLines,
      'expands': instance.expands,
      'maxLength': instance.maxLength,
      'onChanged': instance.onChanged,
      'onTap': instance.onTap,
      'onEditingComplete': instance.onEditingComplete,
      'onFieldSubmitted': instance.onFieldSubmitted,
      'onSaved': instance.onSaved,
      'validator': instance.validator,
      'inputFormatters': instance.inputFormatters,
      'enabled': instance.enabled,
      'cursorWidth': instance.cursorWidth,
      'cursorHeight': instance.cursorHeight,
      'cursorColor': instance.cursorColor,
      'keyboardAppearance': instance.keyboardAppearance,
    };
