// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'editable_text_dj.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

EditableTextDj _$EditableTextDjFromJson(Map<String, dynamic> json) {
  return EditableTextDj(
    key: json['key'],
    controller: json['controller'],
    focusNode: json['focusNode'],
    readOnly: json['readOnly'],
    obscuringCharacter: json['obscuringCharacter'],
    obscureText: json['obscureText'],
    autocorrect: json['autocorrect'],
    smartDashesType: json['smartDashesType'],
    smartQuotesType: json['smartQuotesType'],
    enableSuggestions: json['enableSuggestions'],
    style: json['style'],
    strutStyle: json['strutStyle'],
    cursorColor: json['cursorColor'],
    backgroundCursorColor: json['backgroundCursorColor'],
    textAlign: json['textAlign'],
    textDirection: json['textDirection'],
    locale: json['locale'],
    textScaleFactor: json['textScaleFactor'],
    maxLines: json['maxLines'],
    minLines: json['minLines'],
    expands: json['expands'],
    forceLine: json['forceLine'],
    textHeightBehavior: json['textHeightBehavior'],
    textWidthBasis: json['textWidthBasis'],
    autofocus: json['autofocus'],
    showCursor: json['showCursor'],
    showSelectionHandles: json['showSelectionHandles'],
    selectionColor: json['selectionColor'],
    selectionControls: json['selectionControls'],
    keyboardType: json['keyboardType'],
    textInputAction: json['textInputAction'],
    textCapitalization: json['textCapitalization'],
    onChanged: json['onChanged'],
    onEditingComplete: json['onEditingComplete'],
    onSubmitted: json['onSubmitted'],
    onAppPrivateCommand: json['onAppPrivateCommand'],
    onSelectionChanged: json['onSelectionChanged'],
    onSelectionHandleTapped: json['onSelectionHandleTapped'],
    inputFormatters: json['inputFormatters'],
    mouseCursor: json['mouseCursor'],
    rendererIgnoresPointer: json['rendererIgnoresPointer'],
    cursorWidth: json['cursorWidth'],
    cursorHeight: json['cursorHeight'],
    cursorRadius: json['cursorRadius'],
    cursorOpacityAnimates: json['cursorOpacityAnimates'],
    cursorOffset: json['cursorOffset'],
    paintCursorAboveText: json['paintCursorAboveText'],
    selectionHeightStyle: json['selectionHeightStyle'],
    selectionWidthStyle: json['selectionWidthStyle'],
    baseWidgetDjType: json['baseWidgetDjType'],
  );
}

Map<String, dynamic> _$EditableTextDjToJson(EditableTextDj instance) =>
    <String, dynamic>{
      'baseWidgetDjType': instance.baseWidgetDjType,
      'key': instance.key,
      'controller': instance.controller,
      'focusNode': instance.focusNode,
      'readOnly': instance.readOnly,
      'obscuringCharacter': instance.obscuringCharacter,
      'obscureText': instance.obscureText,
      'autocorrect': instance.autocorrect,
      'smartDashesType': instance.smartDashesType,
      'smartQuotesType': instance.smartQuotesType,
      'enableSuggestions': instance.enableSuggestions,
      'style': instance.style,
      'strutStyle': instance.strutStyle,
      'cursorColor': instance.cursorColor,
      'backgroundCursorColor': instance.backgroundCursorColor,
      'textAlign': instance.textAlign,
      'textDirection': instance.textDirection,
      'locale': instance.locale,
      'textScaleFactor': instance.textScaleFactor,
      'maxLines': instance.maxLines,
      'minLines': instance.minLines,
      'expands': instance.expands,
      'forceLine': instance.forceLine,
      'textHeightBehavior': instance.textHeightBehavior,
      'textWidthBasis': instance.textWidthBasis,
      'autofocus': instance.autofocus,
      'showCursor': instance.showCursor,
      'showSelectionHandles': instance.showSelectionHandles,
      'selectionColor': instance.selectionColor,
      'selectionControls': instance.selectionControls,
      'keyboardType': instance.keyboardType,
      'textInputAction': instance.textInputAction,
      'textCapitalization': instance.textCapitalization,
      'onChanged': instance.onChanged,
      'onEditingComplete': instance.onEditingComplete,
      'onSubmitted': instance.onSubmitted,
      'onAppPrivateCommand': instance.onAppPrivateCommand,
      'onSelectionChanged': instance.onSelectionChanged,
      'onSelectionHandleTapped': instance.onSelectionHandleTapped,
      'inputFormatters': instance.inputFormatters,
      'mouseCursor': instance.mouseCursor,
      'rendererIgnoresPointer': instance.rendererIgnoresPointer,
      'cursorWidth': instance.cursorWidth,
      'cursorHeight': instance.cursorHeight,
      'cursorRadius': instance.cursorRadius,
      'cursorOpacityAnimates': instance.cursorOpacityAnimates,
      'cursorOffset': instance.cursorOffset,
      'paintCursorAboveText': instance.paintCursorAboveText,
      'selectionHeightStyle': instance.selectionHeightStyle,
      'selectionWidthStyle': instance.selectionWidthStyle,
    };
