// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'render_semantics_annotations_dj.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

RenderSemanticsAnnotationsDj _$RenderSemanticsAnnotationsDjFromJson(
    Map<String, dynamic> json) {
  return RenderSemanticsAnnotationsDj(
    child: json['child'],
    container: json['container'],
    explicitChildNodes: json['explicitChildNodes'],
    excludeSemantics: json['excludeSemantics'],
    enabled: json['enabled'],
    checked: json['checked'],
    toggled: json['toggled'],
    selected: json['selected'],
    button: json['button'],
    slider: json['slider'],
    keyboardKey: json['keyboardKey'],
    link: json['link'],
    header: json['header'],
    textField: json['textField'],
    readOnly: json['readOnly'],
    focusable: json['focusable'],
    focused: json['focused'],
    inMutuallyExclusiveGroup: json['inMutuallyExclusiveGroup'],
    obscured: json['obscured'],
    multiline: json['multiline'],
    scopesRoute: json['scopesRoute'],
    namesRoute: json['namesRoute'],
    hidden: json['hidden'],
    image: json['image'],
    liveRegion: json['liveRegion'],
    maxValueLength: json['maxValueLength'],
    currentValueLength: json['currentValueLength'],
    label: json['label'],
    value: json['value'],
    increasedValue: json['increasedValue'],
    decreasedValue: json['decreasedValue'],
    hint: json['hint'],
    hintOverrides: json['hintOverrides'],
    textDirection: json['textDirection'],
    sortKey: json['sortKey'],
    tagForChildren: json['tagForChildren'],
    onTap: json['onTap'],
    onDismiss: json['onDismiss'],
    onLongPress: json['onLongPress'],
    onScrollLeft: json['onScrollLeft'],
    onScrollRight: json['onScrollRight'],
    onScrollUp: json['onScrollUp'],
    onScrollDown: json['onScrollDown'],
    onIncrease: json['onIncrease'],
    onDecrease: json['onDecrease'],
    onCopy: json['onCopy'],
    onCut: json['onCut'],
    onPaste: json['onPaste'],
    onMoveCursorForwardByCharacter: json['onMoveCursorForwardByCharacter'],
    onMoveCursorBackwardByCharacter: json['onMoveCursorBackwardByCharacter'],
    onMoveCursorForwardByWord: json['onMoveCursorForwardByWord'],
    onMoveCursorBackwardByWord: json['onMoveCursorBackwardByWord'],
    onSetSelection: json['onSetSelection'],
    onSetText: json['onSetText'],
    onDidGainAccessibilityFocus: json['onDidGainAccessibilityFocus'],
    onDidLoseAccessibilityFocus: json['onDidLoseAccessibilityFocus'],
    customSemanticsActions: json['customSemanticsActions'],
    baseWidgetDjType: json['baseWidgetDjType'],
  );
}

Map<String, dynamic> _$RenderSemanticsAnnotationsDjToJson(
        RenderSemanticsAnnotationsDj instance) =>
    <String, dynamic>{
      'baseWidgetDjType': instance.baseWidgetDjType,
      'child': instance.child,
      'container': instance.container,
      'explicitChildNodes': instance.explicitChildNodes,
      'excludeSemantics': instance.excludeSemantics,
      'enabled': instance.enabled,
      'checked': instance.checked,
      'toggled': instance.toggled,
      'selected': instance.selected,
      'button': instance.button,
      'slider': instance.slider,
      'keyboardKey': instance.keyboardKey,
      'link': instance.link,
      'header': instance.header,
      'textField': instance.textField,
      'readOnly': instance.readOnly,
      'focusable': instance.focusable,
      'focused': instance.focused,
      'inMutuallyExclusiveGroup': instance.inMutuallyExclusiveGroup,
      'obscured': instance.obscured,
      'multiline': instance.multiline,
      'scopesRoute': instance.scopesRoute,
      'namesRoute': instance.namesRoute,
      'hidden': instance.hidden,
      'image': instance.image,
      'liveRegion': instance.liveRegion,
      'maxValueLength': instance.maxValueLength,
      'currentValueLength': instance.currentValueLength,
      'label': instance.label,
      'value': instance.value,
      'increasedValue': instance.increasedValue,
      'decreasedValue': instance.decreasedValue,
      'hint': instance.hint,
      'hintOverrides': instance.hintOverrides,
      'textDirection': instance.textDirection,
      'sortKey': instance.sortKey,
      'tagForChildren': instance.tagForChildren,
      'onTap': instance.onTap,
      'onDismiss': instance.onDismiss,
      'onLongPress': instance.onLongPress,
      'onScrollLeft': instance.onScrollLeft,
      'onScrollRight': instance.onScrollRight,
      'onScrollUp': instance.onScrollUp,
      'onScrollDown': instance.onScrollDown,
      'onIncrease': instance.onIncrease,
      'onDecrease': instance.onDecrease,
      'onCopy': instance.onCopy,
      'onCut': instance.onCut,
      'onPaste': instance.onPaste,
      'onMoveCursorForwardByCharacter': instance.onMoveCursorForwardByCharacter,
      'onMoveCursorBackwardByCharacter':
          instance.onMoveCursorBackwardByCharacter,
      'onMoveCursorForwardByWord': instance.onMoveCursorForwardByWord,
      'onMoveCursorBackwardByWord': instance.onMoveCursorBackwardByWord,
      'onSetSelection': instance.onSetSelection,
      'onSetText': instance.onSetText,
      'onDidGainAccessibilityFocus': instance.onDidGainAccessibilityFocus,
      'onDidLoseAccessibilityFocus': instance.onDidLoseAccessibilityFocus,
      'customSemanticsActions': instance.customSemanticsActions,
    };
