// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'sliver_app_bar_dj.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

SliverAppBarDj _$SliverAppBarDjFromJson(Map<String, dynamic> json) {
  return SliverAppBarDj(
    key: json['key'],
    leading: json['leading'],
    automaticallyImplyLeading: json['automaticallyImplyLeading'],
    title: json['title'],
    actions: json['actions'],
    flexibleSpace: json['flexibleSpace'],
    bottom: json['bottom'],
    elevation: json['elevation'],
    shadowColor: json['shadowColor'],
    forceElevated: json['forceElevated'],
    backgroundColor: json['backgroundColor'],
    foregroundColor: json['foregroundColor'],
    brightness: json['brightness'],
    iconTheme: json['iconTheme'],
    actionsIconTheme: json['actionsIconTheme'],
    textTheme: json['textTheme'],
    primary: json['primary'],
    centerTitle: json['centerTitle'],
    excludeHeaderSemantics: json['excludeHeaderSemantics'],
    titleSpacing: json['titleSpacing'],
    collapsedHeight: json['collapsedHeight'],
    expandedHeight: json['expandedHeight'],
    floating: json['floating'],
    pinned: json['pinned'],
    snap: json['snap'],
    stretch: json['stretch'],
    stretchTriggerOffset: json['stretchTriggerOffset'],
    onStretchTrigger: json['onStretchTrigger'],
    shape: json['shape'],
    toolbarHeight: json['toolbarHeight'],
    leadingWidth: json['leadingWidth'],
    backwardsCompatibility: json['backwardsCompatibility'],
    toolbarTextStyle: json['toolbarTextStyle'],
    titleTextStyle: json['titleTextStyle'],
    systemOverlayStyle: json['systemOverlayStyle'],
    baseWidgetDjType: json['baseWidgetDjType'],
  );
}

Map<String, dynamic> _$SliverAppBarDjToJson(SliverAppBarDj instance) =>
    <String, dynamic>{
      'baseWidgetDjType': instance.baseWidgetDjType,
      'key': instance.key,
      'leading': instance.leading,
      'automaticallyImplyLeading': instance.automaticallyImplyLeading,
      'title': instance.title,
      'actions': instance.actions,
      'flexibleSpace': instance.flexibleSpace,
      'bottom': instance.bottom,
      'elevation': instance.elevation,
      'shadowColor': instance.shadowColor,
      'forceElevated': instance.forceElevated,
      'backgroundColor': instance.backgroundColor,
      'foregroundColor': instance.foregroundColor,
      'brightness': instance.brightness,
      'iconTheme': instance.iconTheme,
      'actionsIconTheme': instance.actionsIconTheme,
      'textTheme': instance.textTheme,
      'primary': instance.primary,
      'centerTitle': instance.centerTitle,
      'excludeHeaderSemantics': instance.excludeHeaderSemantics,
      'titleSpacing': instance.titleSpacing,
      'collapsedHeight': instance.collapsedHeight,
      'expandedHeight': instance.expandedHeight,
      'floating': instance.floating,
      'pinned': instance.pinned,
      'snap': instance.snap,
      'stretch': instance.stretch,
      'stretchTriggerOffset': instance.stretchTriggerOffset,
      'onStretchTrigger': instance.onStretchTrigger,
      'shape': instance.shape,
      'toolbarHeight': instance.toolbarHeight,
      'leadingWidth': instance.leadingWidth,
      'backwardsCompatibility': instance.backwardsCompatibility,
      'toolbarTextStyle': instance.toolbarTextStyle,
      'titleTextStyle': instance.titleTextStyle,
      'systemOverlayStyle': instance.systemOverlayStyle,
    };
