// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'base_widget_dj.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

BaseWidgetDj _$BaseWidgetDjFromJson(Map<String, dynamic> json) {
  return BaseWidgetDj(
    baseWidgetDjType:
        _$enumDecode(_$WidgetDjTypesEnumMap, json['baseWidgetDjType']),
  );
}

Map<String, dynamic> _$BaseWidgetDjToJson(BaseWidgetDj instance) =>
    <String, dynamic>{
      'baseWidgetDjType': _$WidgetDjTypesEnumMap[instance.baseWidgetDjType],
    };

K _$enumDecode<K, V>(
  Map<K, V> enumValues,
  Object? source, {
  K? unknownValue,
}) {
  if (source == null) {
    throw ArgumentError(
      'A value must be provided. Supported values: '
      '${enumValues.values.join(', ')}',
    );
  }

  return enumValues.entries.singleWhere(
    (e) => e.value == source,
    orElse: () {
      if (unknownValue == null) {
        throw ArgumentError(
          '`$source` is not one of the supported values: '
          '${enumValues.values.join(', ')}',
        );
      }
      return MapEntry(unknownValue, enumValues.values.first);
    },
  ).key;
}

const _$WidgetDjTypesEnumMap = {
  WidgetDjTypes.Animation: 'Animation',
  WidgetDjTypes.AlwaysStoppedAnimation: 'AlwaysStoppedAnimation',
  WidgetDjTypes.CurvedAnimation: 'CurvedAnimation',
  WidgetDjTypes.AnimationMean: 'AnimationMean',
  WidgetDjTypes.AnimationMax: 'AnimationMax',
  WidgetDjTypes.AnimationMin: 'AnimationMin',
  WidgetDjTypes.ParametricCurve: 'ParametricCurve',
  WidgetDjTypes.Curve: 'Curve',
  WidgetDjTypes.SawTooth: 'SawTooth',
  WidgetDjTypes.Interval: 'Interval',
  WidgetDjTypes.Threshold: 'Threshold',
  WidgetDjTypes.Cubic: 'Cubic',
  WidgetDjTypes.Curve2D: 'Curve2D',
  WidgetDjTypes.Curve2DSample: 'Curve2DSample',
  WidgetDjTypes.CatmullRomSpline: 'CatmullRomSpline',
  WidgetDjTypes.CatmullRomCurve: 'CatmullRomCurve',
  WidgetDjTypes.FlippedCurve: 'FlippedCurve',
  WidgetDjTypes.ElasticInCurve: 'ElasticInCurve',
  WidgetDjTypes.ElasticOutCurve: 'ElasticOutCurve',
  WidgetDjTypes.ElasticInOutCurve: 'ElasticInOutCurve',
  WidgetDjTypes.Curves: 'Curves',
  WidgetDjTypes.Animatable: 'Animatable',
  WidgetDjTypes.Tween: 'Tween',
  WidgetDjTypes.ReverseTween: 'ReverseTween',
  WidgetDjTypes.ColorTween: 'ColorTween',
  WidgetDjTypes.SizeTween: 'SizeTween',
  WidgetDjTypes.RectTween: 'RectTween',
  WidgetDjTypes.IntTween: 'IntTween',
  WidgetDjTypes.StepTween: 'StepTween',
  WidgetDjTypes.ConstantTween: 'ConstantTween',
  WidgetDjTypes.CurveTween: 'CurveTween',
  WidgetDjTypes.TweenSequence: 'TweenSequence',
  WidgetDjTypes.FlippedTweenSequence: 'FlippedTweenSequence',
  WidgetDjTypes.TweenSequenceItem: 'TweenSequenceItem',
  WidgetDjTypes.CupertinoActionSheet: 'CupertinoActionSheet',
  WidgetDjTypes.CupertinoActionSheetAction: 'CupertinoActionSheetAction',
  WidgetDjTypes.CupertinoActivityIndicator: 'CupertinoActivityIndicator',
  WidgetDjTypes.CupertinoApp: 'CupertinoApp',
  WidgetDjTypes.CupertinoTabBar: 'CupertinoTabBar',
  WidgetDjTypes.CupertinoButton: 'CupertinoButton',
  WidgetDjTypes.CupertinoColors: 'CupertinoColors',
  WidgetDjTypes.CupertinoDynamicColor: 'CupertinoDynamicColor',
  WidgetDjTypes.CupertinoContextMenu: 'CupertinoContextMenu',
  WidgetDjTypes.CupertinoContextMenuAction: 'CupertinoContextMenuAction',
  WidgetDjTypes.CupertinoDatePicker: 'CupertinoDatePicker',
  WidgetDjTypes.CupertinoTimerPicker: 'CupertinoTimerPicker',
  WidgetDjTypes.CupertinoAlertDialog: 'CupertinoAlertDialog',
  WidgetDjTypes.CupertinoPopupSurface: 'CupertinoPopupSurface',
  WidgetDjTypes.CupertinoDialogAction: 'CupertinoDialogAction',
  WidgetDjTypes.CupertinoFormRow: 'CupertinoFormRow',
  WidgetDjTypes.CupertinoFormSection: 'CupertinoFormSection',
  WidgetDjTypes.CupertinoIcons: 'CupertinoIcons',
  WidgetDjTypes.CupertinoIconThemeData: 'CupertinoIconThemeData',
  WidgetDjTypes.CupertinoUserInterfaceLevel: 'CupertinoUserInterfaceLevel',
  WidgetDjTypes.CupertinoLocalizations: 'CupertinoLocalizations',
  WidgetDjTypes.DefaultCupertinoLocalizations: 'DefaultCupertinoLocalizations',
  WidgetDjTypes.CupertinoNavigationBar: 'CupertinoNavigationBar',
  WidgetDjTypes.CupertinoSliverNavigationBar: 'CupertinoSliverNavigationBar',
  WidgetDjTypes.CupertinoNavigationBarBackButton:
      'CupertinoNavigationBarBackButton',
  WidgetDjTypes.CupertinoPageScaffold: 'CupertinoPageScaffold',
  WidgetDjTypes.CupertinoPicker: 'CupertinoPicker',
  WidgetDjTypes.CupertinoPickerDefaultSelectionOverlay:
      'CupertinoPickerDefaultSelectionOverlay',
  WidgetDjTypes.CupertinoSliverRefreshControl: 'CupertinoSliverRefreshControl',
  WidgetDjTypes.CupertinoPageRoute: 'CupertinoPageRoute',
  WidgetDjTypes.CupertinoPage: 'CupertinoPage',
  WidgetDjTypes.CupertinoPageTransition: 'CupertinoPageTransition',
  WidgetDjTypes.CupertinoFullscreenDialogTransition:
      'CupertinoFullscreenDialogTransition',
  WidgetDjTypes.CupertinoDialogRoute: 'CupertinoDialogRoute',
  WidgetDjTypes.CupertinoScrollbar: 'CupertinoScrollbar',
  WidgetDjTypes.CupertinoSearchTextField: 'CupertinoSearchTextField',
  WidgetDjTypes.CupertinoSegmentedControl: 'CupertinoSegmentedControl',
  WidgetDjTypes.CupertinoSlider: 'CupertinoSlider',
  WidgetDjTypes.CupertinoSlidingSegmentedControl:
      'CupertinoSlidingSegmentedControl',
  WidgetDjTypes.CupertinoSwitch: 'CupertinoSwitch',
  WidgetDjTypes.CupertinoTabController: 'CupertinoTabController',
  WidgetDjTypes.CupertinoTabScaffold: 'CupertinoTabScaffold',
  WidgetDjTypes.RestorableCupertinoTabController:
      'RestorableCupertinoTabController',
  WidgetDjTypes.CupertinoTabView: 'CupertinoTabView',
  WidgetDjTypes.CupertinoTextField: 'CupertinoTextField',
  WidgetDjTypes.CupertinoTextFormFieldRow: 'CupertinoTextFormFieldRow',
  WidgetDjTypes.CupertinoTextSelectionControls:
      'CupertinoTextSelectionControls',
  WidgetDjTypes.CupertinoTextSelectionToolbar: 'CupertinoTextSelectionToolbar',
  WidgetDjTypes.CupertinoTextSelectionToolbarButton:
      'CupertinoTextSelectionToolbarButton',
  WidgetDjTypes.CupertinoTextThemeData: 'CupertinoTextThemeData',
  WidgetDjTypes.CupertinoTheme: 'CupertinoTheme',
  WidgetDjTypes.CupertinoThemeData: 'CupertinoThemeData',
  WidgetDjTypes.NoDefaultCupertinoThemeData: 'NoDefaultCupertinoThemeData',
  WidgetDjTypes.CupertinoThumbPainter: 'CupertinoThumbPainter',
  WidgetDjTypes.Category: 'Category',
  WidgetDjTypes.DocumentationIcon: 'DocumentationIcon',
  WidgetDjTypes.Summary: 'Summary',
  WidgetDjTypes.PartialStackFrame: 'PartialStackFrame',
  WidgetDjTypes.StackFilter: 'StackFilter',
  WidgetDjTypes.RepetitiveStackFrameFilter: 'RepetitiveStackFrameFilter',
  WidgetDjTypes.ErrorDescription: 'ErrorDescription',
  WidgetDjTypes.ErrorSummary: 'ErrorSummary',
  WidgetDjTypes.ErrorHint: 'ErrorHint',
  WidgetDjTypes.ErrorSpacer: 'ErrorSpacer',
  WidgetDjTypes.FlutterErrorDetails: 'FlutterErrorDetails',
  WidgetDjTypes.FlutterError: 'FlutterError',
  WidgetDjTypes.DiagnosticsStackTrace: 'DiagnosticsStackTrace',
  WidgetDjTypes.CachingIterable: 'CachingIterable',
  WidgetDjTypes.Factory: 'Factory',
  WidgetDjTypes.BindingBase: 'BindingBase',
  WidgetDjTypes.BitField: 'BitField',
  WidgetDjTypes.Listenable: 'Listenable',
  WidgetDjTypes.ValueListenable: 'ValueListenable',
  WidgetDjTypes.ChangeNotifier: 'ChangeNotifier',
  WidgetDjTypes.ValueNotifier: 'ValueNotifier',
  WidgetDjTypes.TextTreeConfiguration: 'TextTreeConfiguration',
  WidgetDjTypes.TextTreeRenderer: 'TextTreeRenderer',
  WidgetDjTypes.DiagnosticsNode: 'DiagnosticsNode',
  WidgetDjTypes.MessageProperty: 'MessageProperty',
  WidgetDjTypes.StringProperty: 'StringProperty',
  WidgetDjTypes.DoubleProperty: 'DoubleProperty',
  WidgetDjTypes.IntProperty: 'IntProperty',
  WidgetDjTypes.PercentProperty: 'PercentProperty',
  WidgetDjTypes.FlagProperty: 'FlagProperty',
  WidgetDjTypes.IterableProperty: 'IterableProperty',
  WidgetDjTypes.EnumProperty: 'EnumProperty',
  WidgetDjTypes.ObjectFlagProperty: 'ObjectFlagProperty',
  WidgetDjTypes.FlagsSummary: 'FlagsSummary',
  WidgetDjTypes.DiagnosticsProperty: 'DiagnosticsProperty',
  WidgetDjTypes.DiagnosticableNode: 'DiagnosticableNode',
  WidgetDjTypes.DiagnosticableTreeNode: 'DiagnosticableTreeNode',
  WidgetDjTypes.DiagnosticPropertiesBuilder: 'DiagnosticPropertiesBuilder',
  WidgetDjTypes.DiagnosticableTree: 'DiagnosticableTree',
  WidgetDjTypes.DiagnosticsBlock: 'DiagnosticsBlock',
  WidgetDjTypes.DiagnosticsSerializationDelegate:
      'DiagnosticsSerializationDelegate',
  WidgetDjTypes.Key: 'Key',
  WidgetDjTypes.LocalKey: 'LocalKey',
  WidgetDjTypes.ValueKey: 'ValueKey',
  WidgetDjTypes.LicenseParagraph: 'LicenseParagraph',
  WidgetDjTypes.LicenseEntry: 'LicenseEntry',
  WidgetDjTypes.LicenseEntryWithLineBreaks: 'LicenseEntryWithLineBreaks',
  WidgetDjTypes.LicenseRegistry: 'LicenseRegistry',
  WidgetDjTypes.AbstractNode: 'AbstractNode',
  WidgetDjTypes.ObserverList: 'ObserverList',
  WidgetDjTypes.HashedObserverList: 'HashedObserverList',
  WidgetDjTypes.WriteBuffer: 'WriteBuffer',
  WidgetDjTypes.ReadBuffer: 'ReadBuffer',
  WidgetDjTypes.StackFrame: 'StackFrame',
  WidgetDjTypes.SynchronousFuture: 'SynchronousFuture',
  WidgetDjTypes.Unicode: 'Unicode',
  WidgetDjTypes.GestureArenaMember: 'GestureArenaMember',
  WidgetDjTypes.GestureArenaEntry: 'GestureArenaEntry',
  WidgetDjTypes.GestureArenaManager: 'GestureArenaManager',
  WidgetDjTypes.FlutterErrorDetailsForPointerEventDispatcher:
      'FlutterErrorDetailsForPointerEventDispatcher',
  WidgetDjTypes.PointerEventConverter: 'PointerEventConverter',
  WidgetDjTypes.Drag: 'Drag',
  WidgetDjTypes.DragDownDetails: 'DragDownDetails',
  WidgetDjTypes.DragStartDetails: 'DragStartDetails',
  WidgetDjTypes.DragUpdateDetails: 'DragUpdateDetails',
  WidgetDjTypes.DragEndDetails: 'DragEndDetails',
  WidgetDjTypes.EagerGestureRecognizer: 'EagerGestureRecognizer',
  WidgetDjTypes.PointerEvent: 'PointerEvent',
  WidgetDjTypes.PointerAddedEvent: 'PointerAddedEvent',
  WidgetDjTypes.PointerRemovedEvent: 'PointerRemovedEvent',
  WidgetDjTypes.PointerHoverEvent: 'PointerHoverEvent',
  WidgetDjTypes.PointerEnterEvent: 'PointerEnterEvent',
  WidgetDjTypes.PointerExitEvent: 'PointerExitEvent',
  WidgetDjTypes.PointerDownEvent: 'PointerDownEvent',
  WidgetDjTypes.PointerMoveEvent: 'PointerMoveEvent',
  WidgetDjTypes.PointerUpEvent: 'PointerUpEvent',
  WidgetDjTypes.PointerSignalEvent: 'PointerSignalEvent',
  WidgetDjTypes.PointerScrollEvent: 'PointerScrollEvent',
  WidgetDjTypes.PointerCancelEvent: 'PointerCancelEvent',
  WidgetDjTypes.ForcePressDetails: 'ForcePressDetails',
  WidgetDjTypes.ForcePressGestureRecognizer: 'ForcePressGestureRecognizer',
  WidgetDjTypes.HitTestable: 'HitTestable',
  WidgetDjTypes.HitTestDispatcher: 'HitTestDispatcher',
  WidgetDjTypes.HitTestTarget: 'HitTestTarget',
  WidgetDjTypes.HitTestEntry: 'HitTestEntry',
  WidgetDjTypes.HitTestResult: 'HitTestResult',
  WidgetDjTypes.LongPressStartDetails: 'LongPressStartDetails',
  WidgetDjTypes.LongPressMoveUpdateDetails: 'LongPressMoveUpdateDetails',
  WidgetDjTypes.LongPressEndDetails: 'LongPressEndDetails',
  WidgetDjTypes.LongPressGestureRecognizer: 'LongPressGestureRecognizer',
  WidgetDjTypes.PolynomialFit: 'PolynomialFit',
  WidgetDjTypes.LeastSquaresSolver: 'LeastSquaresSolver',
  WidgetDjTypes.DragGestureRecognizer: 'DragGestureRecognizer',
  WidgetDjTypes.VerticalDragGestureRecognizer: 'VerticalDragGestureRecognizer',
  WidgetDjTypes.HorizontalDragGestureRecognizer:
      'HorizontalDragGestureRecognizer',
  WidgetDjTypes.PanGestureRecognizer: 'PanGestureRecognizer',
  WidgetDjTypes.MultiDragPointerState: 'MultiDragPointerState',
  WidgetDjTypes.MultiDragGestureRecognizer: 'MultiDragGestureRecognizer',
  WidgetDjTypes.ImmediateMultiDragGestureRecognizer:
      'ImmediateMultiDragGestureRecognizer',
  WidgetDjTypes.HorizontalMultiDragGestureRecognizer:
      'HorizontalMultiDragGestureRecognizer',
  WidgetDjTypes.VerticalMultiDragGestureRecognizer:
      'VerticalMultiDragGestureRecognizer',
  WidgetDjTypes.DelayedMultiDragGestureRecognizer:
      'DelayedMultiDragGestureRecognizer',
  WidgetDjTypes.DoubleTapGestureRecognizer: 'DoubleTapGestureRecognizer',
  WidgetDjTypes.MultiTapGestureRecognizer: 'MultiTapGestureRecognizer',
  WidgetDjTypes.PointerRouter: 'PointerRouter',
  WidgetDjTypes.PointerSignalResolver: 'PointerSignalResolver',
  WidgetDjTypes.GestureRecognizer: 'GestureRecognizer',
  WidgetDjTypes.OneSequenceGestureRecognizer: 'OneSequenceGestureRecognizer',
  WidgetDjTypes.PrimaryPointerGestureRecognizer:
      'PrimaryPointerGestureRecognizer',
  WidgetDjTypes.OffsetPair: 'OffsetPair',
  WidgetDjTypes.PointerEventResampler: 'PointerEventResampler',
  WidgetDjTypes.ScaleStartDetails: 'ScaleStartDetails',
  WidgetDjTypes.ScaleUpdateDetails: 'ScaleUpdateDetails',
  WidgetDjTypes.ScaleEndDetails: 'ScaleEndDetails',
  WidgetDjTypes.ScaleGestureRecognizer: 'ScaleGestureRecognizer',
  WidgetDjTypes.TapDownDetails: 'TapDownDetails',
  WidgetDjTypes.TapUpDetails: 'TapUpDetails',
  WidgetDjTypes.BaseTapGestureRecognizer: 'BaseTapGestureRecognizer',
  WidgetDjTypes.TapGestureRecognizer: 'TapGestureRecognizer',
  WidgetDjTypes.GestureArenaTeam: 'GestureArenaTeam',
  WidgetDjTypes.Velocity: 'Velocity',
  WidgetDjTypes.VelocityEstimate: 'VelocityEstimate',
  WidgetDjTypes.VelocityTracker: 'VelocityTracker',
  WidgetDjTypes.IOSScrollViewFlingVelocityTracker:
      'IOSScrollViewFlingVelocityTracker',
  WidgetDjTypes.AboutListTile: 'AboutListTile',
  WidgetDjTypes.AboutDialog: 'AboutDialog',
  WidgetDjTypes.LicensePage: 'LicensePage',
  WidgetDjTypes.AnimatedIcon: 'AnimatedIcon',
  WidgetDjTypes.AnimatedIcons: 'AnimatedIcons',
  WidgetDjTypes.AnimatedIconData: 'AnimatedIconData',
  WidgetDjTypes.MaterialApp: 'MaterialApp',
  WidgetDjTypes.AppBar: 'AppBar',
  WidgetDjTypes.SliverAppBar: 'SliverAppBar',
  WidgetDjTypes.AppBarTheme: 'AppBarTheme',
  WidgetDjTypes.MaterialPointArcTween: 'MaterialPointArcTween',
  WidgetDjTypes.MaterialRectArcTween: 'MaterialRectArcTween',
  WidgetDjTypes.MaterialRectCenterArcTween: 'MaterialRectCenterArcTween',
  WidgetDjTypes.Autocomplete: 'Autocomplete',
  WidgetDjTypes.BackButtonIcon: 'BackButtonIcon',
  WidgetDjTypes.BackButton: 'BackButton',
  WidgetDjTypes.CloseButton: 'CloseButton',
  WidgetDjTypes.MaterialBanner: 'MaterialBanner',
  WidgetDjTypes.MaterialBannerThemeData: 'MaterialBannerThemeData',
  WidgetDjTypes.MaterialBannerTheme: 'MaterialBannerTheme',
  WidgetDjTypes.BottomAppBar: 'BottomAppBar',
  WidgetDjTypes.BottomAppBarTheme: 'BottomAppBarTheme',
  WidgetDjTypes.BottomNavigationBar: 'BottomNavigationBar',
  WidgetDjTypes.BottomNavigationBarThemeData: 'BottomNavigationBarThemeData',
  WidgetDjTypes.BottomNavigationBarTheme: 'BottomNavigationBarTheme',
  WidgetDjTypes.BottomSheet: 'BottomSheet',
  WidgetDjTypes.BottomSheetThemeData: 'BottomSheetThemeData',
  WidgetDjTypes.RawMaterialButton: 'RawMaterialButton',
  WidgetDjTypes.ButtonBar: 'ButtonBar',
  WidgetDjTypes.ButtonBarThemeData: 'ButtonBarThemeData',
  WidgetDjTypes.ButtonBarTheme: 'ButtonBarTheme',
  WidgetDjTypes.ButtonStyle: 'ButtonStyle',
  WidgetDjTypes.ButtonStyleButton: 'ButtonStyleButton',
  WidgetDjTypes.ButtonTheme: 'ButtonTheme',
  WidgetDjTypes.ButtonThemeData: 'ButtonThemeData',
  WidgetDjTypes.CalendarDatePicker: 'CalendarDatePicker',
  WidgetDjTypes.YearPicker: 'YearPicker',
  WidgetDjTypes.Card: 'Card',
  WidgetDjTypes.CardTheme: 'CardTheme',
  WidgetDjTypes.Checkbox: 'Checkbox',
  WidgetDjTypes.CheckboxListTile: 'CheckboxListTile',
  WidgetDjTypes.CheckboxThemeData: 'CheckboxThemeData',
  WidgetDjTypes.CheckboxTheme: 'CheckboxTheme',
  WidgetDjTypes.ChipAttributes: 'ChipAttributes',
  WidgetDjTypes.DeletableChipAttributes: 'DeletableChipAttributes',
  WidgetDjTypes.CheckmarkableChipAttributes: 'CheckmarkableChipAttributes',
  WidgetDjTypes.SelectableChipAttributes: 'SelectableChipAttributes',
  WidgetDjTypes.DisabledChipAttributes: 'DisabledChipAttributes',
  WidgetDjTypes.TappableChipAttributes: 'TappableChipAttributes',
  WidgetDjTypes.Chip: 'Chip',
  WidgetDjTypes.ActionChip: 'ActionChip',
  WidgetDjTypes.ChipTheme: 'ChipTheme',
  WidgetDjTypes.ChipThemeData: 'ChipThemeData',
  WidgetDjTypes.CircleAvatar: 'CircleAvatar',
  WidgetDjTypes.MaterialColor: 'MaterialColor',
  WidgetDjTypes.MaterialAccentColor: 'MaterialAccentColor',
  WidgetDjTypes.Colors: 'Colors',
  WidgetDjTypes.ColorScheme: 'ColorScheme',
  WidgetDjTypes.DataColumn: 'DataColumn',
  WidgetDjTypes.DataRow: 'DataRow',
  WidgetDjTypes.DataCell: 'DataCell',
  WidgetDjTypes.DataTable: 'DataTable',
  WidgetDjTypes.TableRowInkWell: 'TableRowInkWell',
  WidgetDjTypes.DataTableSource: 'DataTableSource',
  WidgetDjTypes.DataTableThemeData: 'DataTableThemeData',
  WidgetDjTypes.DataTableTheme: 'DataTableTheme',
  WidgetDjTypes.DateUtils: 'DateUtils',
  WidgetDjTypes.DateTimeRange: 'DateTimeRange',
  WidgetDjTypes.DayPicker: 'DayPicker',
  WidgetDjTypes.MonthPicker: 'MonthPicker',
  WidgetDjTypes.Dialog: 'Dialog',
  WidgetDjTypes.AlertDialog: 'AlertDialog',
  WidgetDjTypes.SimpleDialogOption: 'SimpleDialogOption',
  WidgetDjTypes.SimpleDialog: 'SimpleDialog',
  WidgetDjTypes.DialogRoute: 'DialogRoute',
  WidgetDjTypes.DialogTheme: 'DialogTheme',
  WidgetDjTypes.Divider: 'Divider',
  WidgetDjTypes.VerticalDivider: 'VerticalDivider',
  WidgetDjTypes.DividerThemeData: 'DividerThemeData',
  WidgetDjTypes.DividerTheme: 'DividerTheme',
  WidgetDjTypes.Drawer: 'Drawer',
  WidgetDjTypes.DrawerController: 'DrawerController',
  WidgetDjTypes.DrawerControllerState: 'DrawerControllerState',
  WidgetDjTypes.DrawerHeader: 'DrawerHeader',
  WidgetDjTypes.DropdownMenuItem: 'DropdownMenuItem',
  WidgetDjTypes.DropdownButtonHideUnderline: 'DropdownButtonHideUnderline',
  WidgetDjTypes.DropdownButton: 'DropdownButton',
  WidgetDjTypes.DropdownButtonFormField: 'DropdownButtonFormField',
  WidgetDjTypes.ElevatedButton: 'ElevatedButton',
  WidgetDjTypes.ElevatedButtonThemeData: 'ElevatedButtonThemeData',
  WidgetDjTypes.ElevatedButtonTheme: 'ElevatedButtonTheme',
  WidgetDjTypes.ElevationOverlay: 'ElevationOverlay',
  WidgetDjTypes.ExpandIcon: 'ExpandIcon',
  WidgetDjTypes.ExpansionPanel: 'ExpansionPanel',
  WidgetDjTypes.ExpansionPanelRadio: 'ExpansionPanelRadio',
  WidgetDjTypes.ExpansionPanelList: 'ExpansionPanelList',
  WidgetDjTypes.ExpansionTile: 'ExpansionTile',
  WidgetDjTypes.Feedback: 'Feedback',
  WidgetDjTypes.FlatButton: 'FlatButton',
  WidgetDjTypes.FlexibleSpaceBar: 'FlexibleSpaceBar',
  WidgetDjTypes.FlexibleSpaceBarSettings: 'FlexibleSpaceBarSettings',
  WidgetDjTypes.FloatingActionButton: 'FloatingActionButton',
  WidgetDjTypes.FloatingActionButtonLocation: 'FloatingActionButtonLocation',
  WidgetDjTypes.StandardFabLocation: 'StandardFabLocation',
  WidgetDjTypes.FloatingActionButtonAnimator: 'FloatingActionButtonAnimator',
  WidgetDjTypes.FloatingActionButtonThemeData: 'FloatingActionButtonThemeData',
  WidgetDjTypes.FlutterLogo: 'FlutterLogo',
  WidgetDjTypes.GridTile: 'GridTile',
  WidgetDjTypes.GridTileBar: 'GridTileBar',
  WidgetDjTypes.Icons: 'Icons',
  WidgetDjTypes.IconButton: 'IconButton',
  WidgetDjTypes.Ink: 'Ink',
  WidgetDjTypes.InkDecoration: 'InkDecoration',
  WidgetDjTypes.InkHighlight: 'InkHighlight',
  WidgetDjTypes.InkRipple: 'InkRipple',
  WidgetDjTypes.InkSplash: 'InkSplash',
  WidgetDjTypes.InteractiveInkFeature: 'InteractiveInkFeature',
  WidgetDjTypes.InteractiveInkFeatureFactory: 'InteractiveInkFeatureFactory',
  WidgetDjTypes.InkResponse: 'InkResponse',
  WidgetDjTypes.InputBorder: 'InputBorder',
  WidgetDjTypes.UnderlineInputBorder: 'UnderlineInputBorder',
  WidgetDjTypes.OutlineInputBorder: 'OutlineInputBorder',
  WidgetDjTypes.InputDatePickerFormField: 'InputDatePickerFormField',
  WidgetDjTypes.InputDecorator: 'InputDecorator',
  WidgetDjTypes.InputDecoration: 'InputDecoration',
  WidgetDjTypes.InputDecorationTheme: 'InputDecorationTheme',
  WidgetDjTypes.ListTileTheme: 'ListTileTheme',
  WidgetDjTypes.ListTile: 'ListTile',
  WidgetDjTypes.MaterialInkController: 'MaterialInkController',
  WidgetDjTypes.Material: 'Material',
  WidgetDjTypes.InkFeature: 'InkFeature',
  WidgetDjTypes.ShapeBorderTween: 'ShapeBorderTween',
  WidgetDjTypes.MaterialButton: 'MaterialButton',
  WidgetDjTypes.MaterialLocalizations: 'MaterialLocalizations',
  WidgetDjTypes.DefaultMaterialLocalizations: 'DefaultMaterialLocalizations',
  WidgetDjTypes.MaterialStateColor: 'MaterialStateColor',
  WidgetDjTypes.MaterialStateMouseCursor: 'MaterialStateMouseCursor',
  WidgetDjTypes.MaterialStateBorderSide: 'MaterialStateBorderSide',
  WidgetDjTypes.MaterialStateOutlinedBorder: 'MaterialStateOutlinedBorder',
  WidgetDjTypes.MaterialStateProperty: 'MaterialStateProperty',
  WidgetDjTypes.MergeableMaterialItem: 'MergeableMaterialItem',
  WidgetDjTypes.MaterialSlice: 'MaterialSlice',
  WidgetDjTypes.MaterialGap: 'MaterialGap',
  WidgetDjTypes.MergeableMaterial: 'MergeableMaterial',
  WidgetDjTypes.NavigationRail: 'NavigationRail',
  WidgetDjTypes.NavigationRailDestination: 'NavigationRailDestination',
  WidgetDjTypes.NavigationRailThemeData: 'NavigationRailThemeData',
  WidgetDjTypes.NavigationRailTheme: 'NavigationRailTheme',
  WidgetDjTypes.OutlinedButton: 'OutlinedButton',
  WidgetDjTypes.OutlinedButtonThemeData: 'OutlinedButtonThemeData',
  WidgetDjTypes.OutlinedButtonTheme: 'OutlinedButtonTheme',
  WidgetDjTypes.OutlineButton: 'OutlineButton',
  WidgetDjTypes.MaterialPageRoute: 'MaterialPageRoute',
  WidgetDjTypes.MaterialPage: 'MaterialPage',
  WidgetDjTypes.PageTransitionsBuilder: 'PageTransitionsBuilder',
  WidgetDjTypes.FadeUpwardsPageTransitionsBuilder:
      'FadeUpwardsPageTransitionsBuilder',
  WidgetDjTypes.OpenUpwardsPageTransitionsBuilder:
      'OpenUpwardsPageTransitionsBuilder',
  WidgetDjTypes.ZoomPageTransitionsBuilder: 'ZoomPageTransitionsBuilder',
  WidgetDjTypes.CupertinoPageTransitionsBuilder:
      'CupertinoPageTransitionsBuilder',
  WidgetDjTypes.PageTransitionsTheme: 'PageTransitionsTheme',
  WidgetDjTypes.PaginatedDataTable: 'PaginatedDataTable',
  WidgetDjTypes.PaginatedDataTableState: 'PaginatedDataTableState',
  WidgetDjTypes.PopupMenuEntry: 'PopupMenuEntry',
  WidgetDjTypes.PopupMenuDivider: 'PopupMenuDivider',
  WidgetDjTypes.PopupMenuItem: 'PopupMenuItem',
  WidgetDjTypes.PopupMenuItemState: 'PopupMenuItemState',
  WidgetDjTypes.CheckedPopupMenuItem: 'CheckedPopupMenuItem',
  WidgetDjTypes.PopupMenuButton: 'PopupMenuButton',
  WidgetDjTypes.PopupMenuButtonState: 'PopupMenuButtonState',
  WidgetDjTypes.PopupMenuThemeData: 'PopupMenuThemeData',
  WidgetDjTypes.PopupMenuTheme: 'PopupMenuTheme',
  WidgetDjTypes.ProgressIndicator: 'ProgressIndicator',
  WidgetDjTypes.LinearProgressIndicator: 'LinearProgressIndicator',
  WidgetDjTypes.CircularProgressIndicator: 'CircularProgressIndicator',
  WidgetDjTypes.RefreshProgressIndicator: 'RefreshProgressIndicator',
  WidgetDjTypes.Radio: 'Radio',
  WidgetDjTypes.RadioListTile: 'RadioListTile',
  WidgetDjTypes.RadioThemeData: 'RadioThemeData',
  WidgetDjTypes.RadioTheme: 'RadioTheme',
  WidgetDjTypes.RaisedButton: 'RaisedButton',
  WidgetDjTypes.RangeSlider: 'RangeSlider',
  WidgetDjTypes.RefreshIndicator: 'RefreshIndicator',
  WidgetDjTypes.RefreshIndicatorState: 'RefreshIndicatorState',
  WidgetDjTypes.ReorderableListView: 'ReorderableListView',
  WidgetDjTypes.ScaffoldMessenger: 'ScaffoldMessenger',
  WidgetDjTypes.ScaffoldMessengerState: 'ScaffoldMessengerState',
  WidgetDjTypes.ScaffoldPrelayoutGeometry: 'ScaffoldPrelayoutGeometry',
  WidgetDjTypes.ScaffoldGeometry: 'ScaffoldGeometry',
  WidgetDjTypes.Scaffold: 'Scaffold',
  WidgetDjTypes.ScaffoldState: 'ScaffoldState',
  WidgetDjTypes.ScaffoldFeatureController: 'ScaffoldFeatureController',
  WidgetDjTypes.PersistentBottomSheetController:
      'PersistentBottomSheetController',
  WidgetDjTypes.Scrollbar: 'Scrollbar',
  WidgetDjTypes.ScrollbarThemeData: 'ScrollbarThemeData',
  WidgetDjTypes.ScrollbarTheme: 'ScrollbarTheme',
  WidgetDjTypes.SearchDelegate: 'SearchDelegate',
  WidgetDjTypes.SelectableText: 'SelectableText',
  WidgetDjTypes.Slider: 'Slider',
  WidgetDjTypes.SliderTheme: 'SliderTheme',
  WidgetDjTypes.SliderThemeData: 'SliderThemeData',
  WidgetDjTypes.SliderComponentShape: 'SliderComponentShape',
  WidgetDjTypes.SliderTickMarkShape: 'SliderTickMarkShape',
  WidgetDjTypes.SliderTrackShape: 'SliderTrackShape',
  WidgetDjTypes.RangeSliderThumbShape: 'RangeSliderThumbShape',
  WidgetDjTypes.RangeSliderValueIndicatorShape:
      'RangeSliderValueIndicatorShape',
  WidgetDjTypes.RangeSliderTickMarkShape: 'RangeSliderTickMarkShape',
  WidgetDjTypes.RangeSliderTrackShape: 'RangeSliderTrackShape',
  WidgetDjTypes.BaseSliderTrackShape: 'BaseSliderTrackShape',
  WidgetDjTypes.RectangularSliderTrackShape: 'RectangularSliderTrackShape',
  WidgetDjTypes.RoundedRectSliderTrackShape: 'RoundedRectSliderTrackShape',
  WidgetDjTypes.RectangularRangeSliderTrackShape:
      'RectangularRangeSliderTrackShape',
  WidgetDjTypes.RoundedRectRangeSliderTrackShape:
      'RoundedRectRangeSliderTrackShape',
  WidgetDjTypes.RoundSliderTickMarkShape: 'RoundSliderTickMarkShape',
  WidgetDjTypes.RoundRangeSliderTickMarkShape: 'RoundRangeSliderTickMarkShape',
  WidgetDjTypes.RoundSliderThumbShape: 'RoundSliderThumbShape',
  WidgetDjTypes.RoundRangeSliderThumbShape: 'RoundRangeSliderThumbShape',
  WidgetDjTypes.RoundSliderOverlayShape: 'RoundSliderOverlayShape',
  WidgetDjTypes.RectangularSliderValueIndicatorShape:
      'RectangularSliderValueIndicatorShape',
  WidgetDjTypes.PaddleSliderValueIndicatorShape:
      'PaddleSliderValueIndicatorShape',
  WidgetDjTypes.PaddleRangeSliderValueIndicatorShape:
      'PaddleRangeSliderValueIndicatorShape',
  WidgetDjTypes.RangeValues: 'RangeValues',
  WidgetDjTypes.RangeLabels: 'RangeLabels',
  WidgetDjTypes.SnackBarAction: 'SnackBarAction',
  WidgetDjTypes.SnackBar: 'SnackBar',
  WidgetDjTypes.SnackBarThemeData: 'SnackBarThemeData',
  WidgetDjTypes.Step: 'Step',
  WidgetDjTypes.Stepper: 'Stepper',
  WidgetDjTypes.Switch: 'Switch',
  WidgetDjTypes.SwitchListTile: 'SwitchListTile',
  WidgetDjTypes.SwitchThemeData: 'SwitchThemeData',
  WidgetDjTypes.SwitchTheme: 'SwitchTheme',
  WidgetDjTypes.Tab: 'Tab',
  WidgetDjTypes.TabBar: 'TabBar',
  WidgetDjTypes.TabBarView: 'TabBarView',
  WidgetDjTypes.TabPageSelectorIndicator: 'TabPageSelectorIndicator',
  WidgetDjTypes.TabPageSelector: 'TabPageSelector',
  WidgetDjTypes.TabBarTheme: 'TabBarTheme',
  WidgetDjTypes.TabController: 'TabController',
  WidgetDjTypes.DefaultTabController: 'DefaultTabController',
  WidgetDjTypes.UnderlineTabIndicator: 'UnderlineTabIndicator',
  WidgetDjTypes.TextButton: 'TextButton',
  WidgetDjTypes.TextButtonThemeData: 'TextButtonThemeData',
  WidgetDjTypes.TextButtonTheme: 'TextButtonTheme',
  WidgetDjTypes.TextField: 'TextField',
  WidgetDjTypes.TextFormField: 'TextFormField',
  WidgetDjTypes.MaterialTextSelectionControls: 'MaterialTextSelectionControls',
  WidgetDjTypes.TextSelectionThemeData: 'TextSelectionThemeData',
  WidgetDjTypes.TextSelectionTheme: 'TextSelectionTheme',
  WidgetDjTypes.TextSelectionToolbar: 'TextSelectionToolbar',
  WidgetDjTypes.TextSelectionToolbarTextButton:
      'TextSelectionToolbarTextButton',
  WidgetDjTypes.TextTheme: 'TextTheme',
  WidgetDjTypes.Theme: 'Theme',
  WidgetDjTypes.ThemeDataTween: 'ThemeDataTween',
  WidgetDjTypes.AnimatedTheme: 'AnimatedTheme',
  WidgetDjTypes.ThemeData: 'ThemeData',
  WidgetDjTypes.MaterialBasedCupertinoThemeData:
      'MaterialBasedCupertinoThemeData',
  WidgetDjTypes.VisualDensity: 'VisualDensity',
  WidgetDjTypes.TimeOfDay: 'TimeOfDay',
  WidgetDjTypes.TimePickerThemeData: 'TimePickerThemeData',
  WidgetDjTypes.TimePickerTheme: 'TimePickerTheme',
  WidgetDjTypes.RenderToggleable: 'RenderToggleable',
  WidgetDjTypes.ToggleButtons: 'ToggleButtons',
  WidgetDjTypes.ToggleButtonsThemeData: 'ToggleButtonsThemeData',
  WidgetDjTypes.ToggleButtonsTheme: 'ToggleButtonsTheme',
  WidgetDjTypes.Tooltip: 'Tooltip',
  WidgetDjTypes.TooltipThemeData: 'TooltipThemeData',
  WidgetDjTypes.TooltipTheme: 'TooltipTheme',
  WidgetDjTypes.Typography: 'Typography',
  WidgetDjTypes.UserAccountsDrawerHeader: 'UserAccountsDrawerHeader',
  WidgetDjTypes.AlignmentGeometry: 'AlignmentGeometry',
  WidgetDjTypes.Alignment: 'Alignment',
  WidgetDjTypes.AlignmentDirectional: 'AlignmentDirectional',
  WidgetDjTypes.TextAlignVertical: 'TextAlignVertical',
  WidgetDjTypes.BeveledRectangleBorder: 'BeveledRectangleBorder',
  WidgetDjTypes.BorderSide: 'BorderSide',
  WidgetDjTypes.ShapeBorder: 'ShapeBorder',
  WidgetDjTypes.OutlinedBorder: 'OutlinedBorder',
  WidgetDjTypes.BorderRadiusGeometry: 'BorderRadiusGeometry',
  WidgetDjTypes.BorderRadius: 'BorderRadius',
  WidgetDjTypes.BorderRadiusDirectional: 'BorderRadiusDirectional',
  WidgetDjTypes.BoxBorder: 'BoxBorder',
  WidgetDjTypes.Border: 'Border',
  WidgetDjTypes.BorderDirectional: 'BorderDirectional',
  WidgetDjTypes.BoxDecoration: 'BoxDecoration',
  WidgetDjTypes.FittedSizes: 'FittedSizes',
  WidgetDjTypes.BoxShadow: 'BoxShadow',
  WidgetDjTypes.CircleBorder: 'CircleBorder',
  WidgetDjTypes.ClipContext: 'ClipContext',
  WidgetDjTypes.HSVColor: 'HSVColor',
  WidgetDjTypes.HSLColor: 'HSLColor',
  WidgetDjTypes.ColorSwatch: 'ColorSwatch',
  WidgetDjTypes.ColorProperty: 'ColorProperty',
  WidgetDjTypes.ContinuousRectangleBorder: 'ContinuousRectangleBorder',
  WidgetDjTypes.ImageSizeInfo: 'ImageSizeInfo',
  WidgetDjTypes.Decoration: 'Decoration',
  WidgetDjTypes.BoxPainter: 'BoxPainter',
  WidgetDjTypes.DecorationImage: 'DecorationImage',
  WidgetDjTypes.DecorationImagePainter: 'DecorationImagePainter',
  WidgetDjTypes.EdgeInsetsGeometry: 'EdgeInsetsGeometry',
  WidgetDjTypes.EdgeInsets: 'EdgeInsets',
  WidgetDjTypes.EdgeInsetsDirectional: 'EdgeInsetsDirectional',
  WidgetDjTypes.FlutterLogoDecoration: 'FlutterLogoDecoration',
  WidgetDjTypes.FractionalOffset: 'FractionalOffset',
  WidgetDjTypes.GradientTransform: 'GradientTransform',
  WidgetDjTypes.GradientRotation: 'GradientRotation',
  WidgetDjTypes.Gradient: 'Gradient',
  WidgetDjTypes.LinearGradient: 'LinearGradient',
  WidgetDjTypes.RadialGradient: 'RadialGradient',
  WidgetDjTypes.SweepGradient: 'SweepGradient',
  WidgetDjTypes.ImageCache: 'ImageCache',
  WidgetDjTypes.ImageCacheStatus: 'ImageCacheStatus',
  WidgetDjTypes.ImageConfiguration: 'ImageConfiguration',
  WidgetDjTypes.ImageProvider: 'ImageProvider',
  WidgetDjTypes.AssetBundleImageKey: 'AssetBundleImageKey',
  WidgetDjTypes.AssetBundleImageProvider: 'AssetBundleImageProvider',
  WidgetDjTypes.ResizeImage: 'ResizeImage',
  WidgetDjTypes.NetworkImage: 'NetworkImage',
  WidgetDjTypes.FileImage: 'FileImage',
  WidgetDjTypes.MemoryImage: 'MemoryImage',
  WidgetDjTypes.ExactAssetImage: 'ExactAssetImage',
  WidgetDjTypes.NetworkImageLoadException: 'NetworkImageLoadException',
  WidgetDjTypes.AssetImage: 'AssetImage',
  WidgetDjTypes.ImageInfo: 'ImageInfo',
  WidgetDjTypes.ImageStreamListener: 'ImageStreamListener',
  WidgetDjTypes.ImageChunkEvent: 'ImageChunkEvent',
  WidgetDjTypes.ImageStream: 'ImageStream',
  WidgetDjTypes.ImageStreamCompleterHandle: 'ImageStreamCompleterHandle',
  WidgetDjTypes.ImageStreamCompleter: 'ImageStreamCompleter',
  WidgetDjTypes.OneFrameImageStreamCompleter: 'OneFrameImageStreamCompleter',
  WidgetDjTypes.MultiFrameImageStreamCompleter:
      'MultiFrameImageStreamCompleter',
  WidgetDjTypes.Accumulator: 'Accumulator',
  WidgetDjTypes.InlineSpanSemanticsInformation:
      'InlineSpanSemanticsInformation',
  WidgetDjTypes.InlineSpan: 'InlineSpan',
  WidgetDjTypes.MatrixUtils: 'MatrixUtils',
  WidgetDjTypes.TransformProperty: 'TransformProperty',
  WidgetDjTypes.NotchedShape: 'NotchedShape',
  WidgetDjTypes.CircularNotchedRectangle: 'CircularNotchedRectangle',
  WidgetDjTypes.AutomaticNotchedShape: 'AutomaticNotchedShape',
  WidgetDjTypes.PlaceholderSpan: 'PlaceholderSpan',
  WidgetDjTypes.RoundedRectangleBorder: 'RoundedRectangleBorder',
  WidgetDjTypes.ShaderWarmUp: 'ShaderWarmUp',
  WidgetDjTypes.DefaultShaderWarmUp: 'DefaultShaderWarmUp',
  WidgetDjTypes.ShapeDecoration: 'ShapeDecoration',
  WidgetDjTypes.StadiumBorder: 'StadiumBorder',
  WidgetDjTypes.StrutStyle: 'StrutStyle',
  WidgetDjTypes.PlaceholderDimensions: 'PlaceholderDimensions',
  WidgetDjTypes.TextPainter: 'TextPainter',
  WidgetDjTypes.TextSpan: 'TextSpan',
  WidgetDjTypes.TextStyle: 'TextStyle',
  WidgetDjTypes.ClampedSimulation: 'ClampedSimulation',
  WidgetDjTypes.FrictionSimulation: 'FrictionSimulation',
  WidgetDjTypes.BoundedFrictionSimulation: 'BoundedFrictionSimulation',
  WidgetDjTypes.GravitySimulation: 'GravitySimulation',
  WidgetDjTypes.Simulation: 'Simulation',
  WidgetDjTypes.SpringDescription: 'SpringDescription',
  WidgetDjTypes.SpringSimulation: 'SpringSimulation',
  WidgetDjTypes.ScrollSpringSimulation: 'ScrollSpringSimulation',
  WidgetDjTypes.Tolerance: 'Tolerance',
  WidgetDjTypes.RenderAnimatedSize: 'RenderAnimatedSize',
  WidgetDjTypes.RenderingFlutterBinding: 'RenderingFlutterBinding',
  WidgetDjTypes.BoxConstraints: 'BoxConstraints',
  WidgetDjTypes.BoxHitTestResult: 'BoxHitTestResult',
  WidgetDjTypes.BoxHitTestEntry: 'BoxHitTestEntry',
  WidgetDjTypes.BoxParentData: 'BoxParentData',
  WidgetDjTypes.ContainerBoxParentData: 'ContainerBoxParentData',
  WidgetDjTypes.RenderBox: 'RenderBox',
  WidgetDjTypes.MultiChildLayoutParentData: 'MultiChildLayoutParentData',
  WidgetDjTypes.MultiChildLayoutDelegate: 'MultiChildLayoutDelegate',
  WidgetDjTypes.CustomPainter: 'CustomPainter',
  WidgetDjTypes.CustomPainterSemantics: 'CustomPainterSemantics',
  WidgetDjTypes.RenderCustomPaint: 'RenderCustomPaint',
  WidgetDjTypes.TextSelectionPoint: 'TextSelectionPoint',
  WidgetDjTypes.RenderEditable: 'RenderEditable',
  WidgetDjTypes.RenderErrorBox: 'RenderErrorBox',
  WidgetDjTypes.FlexParentData: 'FlexParentData',
  WidgetDjTypes.FlowPaintingContext: 'FlowPaintingContext',
  WidgetDjTypes.FlowDelegate: 'FlowDelegate',
  WidgetDjTypes.FlowParentData: 'FlowParentData',
  WidgetDjTypes.RenderImage: 'RenderImage',
  WidgetDjTypes.AnnotationEntry: 'AnnotationEntry',
  WidgetDjTypes.AnnotationResult: 'AnnotationResult',
  WidgetDjTypes.Layer: 'Layer',
  WidgetDjTypes.PictureLayer: 'PictureLayer',
  WidgetDjTypes.TextureLayer: 'TextureLayer',
  WidgetDjTypes.PlatformViewLayer: 'PlatformViewLayer',
  WidgetDjTypes.PerformanceOverlayLayer: 'PerformanceOverlayLayer',
  WidgetDjTypes.ContainerLayer: 'ContainerLayer',
  WidgetDjTypes.OffsetLayer: 'OffsetLayer',
  WidgetDjTypes.ClipRectLayer: 'ClipRectLayer',
  WidgetDjTypes.ClipRRectLayer: 'ClipRRectLayer',
  WidgetDjTypes.ClipPathLayer: 'ClipPathLayer',
  WidgetDjTypes.ColorFilterLayer: 'ColorFilterLayer',
  WidgetDjTypes.ImageFilterLayer: 'ImageFilterLayer',
  WidgetDjTypes.TransformLayer: 'TransformLayer',
  WidgetDjTypes.OpacityLayer: 'OpacityLayer',
  WidgetDjTypes.ShaderMaskLayer: 'ShaderMaskLayer',
  WidgetDjTypes.BackdropFilterLayer: 'BackdropFilterLayer',
  WidgetDjTypes.PhysicalModelLayer: 'PhysicalModelLayer',
  WidgetDjTypes.LayerLink: 'LayerLink',
  WidgetDjTypes.LeaderLayer: 'LeaderLayer',
  WidgetDjTypes.FollowerLayer: 'FollowerLayer',
  WidgetDjTypes.AnnotatedRegionLayer: 'AnnotatedRegionLayer',
  WidgetDjTypes.ChildLayoutHelper: 'ChildLayoutHelper',
  WidgetDjTypes.ListBodyParentData: 'ListBodyParentData',
  WidgetDjTypes.ListWheelChildManager: 'ListWheelChildManager',
  WidgetDjTypes.ListWheelParentData: 'ListWheelParentData',
  WidgetDjTypes.MouseCursorSession: 'MouseCursorSession',
  WidgetDjTypes.MouseCursor: 'MouseCursor',
  WidgetDjTypes.SystemMouseCursor: 'SystemMouseCursor',
  WidgetDjTypes.SystemMouseCursors: 'SystemMouseCursors',
  WidgetDjTypes.MouseTrackerAnnotation: 'MouseTrackerAnnotation',
  WidgetDjTypes.MouseTrackerUpdateDetails: 'MouseTrackerUpdateDetails',
  WidgetDjTypes.BaseMouseTracker: 'BaseMouseTracker',
  WidgetDjTypes.ParentData: 'ParentData',
  WidgetDjTypes.PaintingContext: 'PaintingContext',
  WidgetDjTypes.Constraints: 'Constraints',
  WidgetDjTypes.SemanticsHandle: 'SemanticsHandle',
  WidgetDjTypes.PipelineOwner: 'PipelineOwner',
  WidgetDjTypes.RenderObject: 'RenderObject',
  WidgetDjTypes.DiagnosticsDebugCreator: 'DiagnosticsDebugCreator',
  WidgetDjTypes.TextParentData: 'TextParentData',
  WidgetDjTypes.PlaceholderSpanIndexSemanticsTag:
      'PlaceholderSpanIndexSemanticsTag',
  WidgetDjTypes.RenderPerformanceOverlay: 'RenderPerformanceOverlay',
  WidgetDjTypes.RenderAndroidView: 'RenderAndroidView',
  WidgetDjTypes.RenderUiKitView: 'RenderUiKitView',
  WidgetDjTypes.PlatformViewRenderBox: 'PlatformViewRenderBox',
  WidgetDjTypes.RenderProxyBox: 'RenderProxyBox',
  WidgetDjTypes.RenderProxyBoxWithHitTestBehavior:
      'RenderProxyBoxWithHitTestBehavior',
  WidgetDjTypes.RenderConstrainedBox: 'RenderConstrainedBox',
  WidgetDjTypes.RenderLimitedBox: 'RenderLimitedBox',
  WidgetDjTypes.RenderAspectRatio: 'RenderAspectRatio',
  WidgetDjTypes.RenderIntrinsicWidth: 'RenderIntrinsicWidth',
  WidgetDjTypes.RenderIntrinsicHeight: 'RenderIntrinsicHeight',
  WidgetDjTypes.RenderOpacity: 'RenderOpacity',
  WidgetDjTypes.RenderAnimatedOpacity: 'RenderAnimatedOpacity',
  WidgetDjTypes.RenderShaderMask: 'RenderShaderMask',
  WidgetDjTypes.RenderBackdropFilter: 'RenderBackdropFilter',
  WidgetDjTypes.CustomClipper: 'CustomClipper',
  WidgetDjTypes.ShapeBorderClipper: 'ShapeBorderClipper',
  WidgetDjTypes.RenderClipRect: 'RenderClipRect',
  WidgetDjTypes.RenderClipRRect: 'RenderClipRRect',
  WidgetDjTypes.RenderClipOval: 'RenderClipOval',
  WidgetDjTypes.RenderClipPath: 'RenderClipPath',
  WidgetDjTypes.RenderPhysicalModel: 'RenderPhysicalModel',
  WidgetDjTypes.RenderPhysicalShape: 'RenderPhysicalShape',
  WidgetDjTypes.RenderDecoratedBox: 'RenderDecoratedBox',
  WidgetDjTypes.RenderTransform: 'RenderTransform',
  WidgetDjTypes.RenderFittedBox: 'RenderFittedBox',
  WidgetDjTypes.RenderFractionalTranslation: 'RenderFractionalTranslation',
  WidgetDjTypes.RenderPointerListener: 'RenderPointerListener',
  WidgetDjTypes.RenderMouseRegion: 'RenderMouseRegion',
  WidgetDjTypes.RenderRepaintBoundary: 'RenderRepaintBoundary',
  WidgetDjTypes.RenderIgnorePointer: 'RenderIgnorePointer',
  WidgetDjTypes.RenderOffstage: 'RenderOffstage',
  WidgetDjTypes.RenderAbsorbPointer: 'RenderAbsorbPointer',
  WidgetDjTypes.RenderMetaData: 'RenderMetaData',
  WidgetDjTypes.RenderSemanticsGestureHandler: 'RenderSemanticsGestureHandler',
  WidgetDjTypes.RenderSemanticsAnnotations: 'RenderSemanticsAnnotations',
  WidgetDjTypes.RenderBlockSemantics: 'RenderBlockSemantics',
  WidgetDjTypes.RenderMergeSemantics: 'RenderMergeSemantics',
  WidgetDjTypes.RenderExcludeSemantics: 'RenderExcludeSemantics',
  WidgetDjTypes.RenderIndexedSemantics: 'RenderIndexedSemantics',
  WidgetDjTypes.RenderLeaderLayer: 'RenderLeaderLayer',
  WidgetDjTypes.RenderFollowerLayer: 'RenderFollowerLayer',
  WidgetDjTypes.RenderAnnotatedRegion: 'RenderAnnotatedRegion',
  WidgetDjTypes.RenderProxySliver: 'RenderProxySliver',
  WidgetDjTypes.RenderSliverOpacity: 'RenderSliverOpacity',
  WidgetDjTypes.RenderSliverIgnorePointer: 'RenderSliverIgnorePointer',
  WidgetDjTypes.RenderSliverOffstage: 'RenderSliverOffstage',
  WidgetDjTypes.RenderRotatedBox: 'RenderRotatedBox',
  WidgetDjTypes.RenderShiftedBox: 'RenderShiftedBox',
  WidgetDjTypes.RenderPadding: 'RenderPadding',
  WidgetDjTypes.RenderAligningShiftedBox: 'RenderAligningShiftedBox',
  WidgetDjTypes.RenderPositionedBox: 'RenderPositionedBox',
  WidgetDjTypes.RenderConstrainedOverflowBox: 'RenderConstrainedOverflowBox',
  WidgetDjTypes.RenderUnconstrainedBox: 'RenderUnconstrainedBox',
  WidgetDjTypes.RenderSizedOverflowBox: 'RenderSizedOverflowBox',
  WidgetDjTypes.RenderFractionallySizedOverflowBox:
      'RenderFractionallySizedOverflowBox',
  WidgetDjTypes.SingleChildLayoutDelegate: 'SingleChildLayoutDelegate',
  WidgetDjTypes.RenderCustomSingleChildLayoutBox:
      'RenderCustomSingleChildLayoutBox',
  WidgetDjTypes.RenderBaseline: 'RenderBaseline',
  WidgetDjTypes.SliverConstraints: 'SliverConstraints',
  WidgetDjTypes.SliverGeometry: 'SliverGeometry',
  WidgetDjTypes.SliverHitTestResult: 'SliverHitTestResult',
  WidgetDjTypes.SliverHitTestEntry: 'SliverHitTestEntry',
  WidgetDjTypes.SliverLogicalParentData: 'SliverLogicalParentData',
  WidgetDjTypes.SliverLogicalContainerParentData:
      'SliverLogicalContainerParentData',
  WidgetDjTypes.SliverPhysicalContainerParentData:
      'SliverPhysicalContainerParentData',
  WidgetDjTypes.RenderSliver: 'RenderSliver',
  WidgetDjTypes.RenderSliverHelpers: 'RenderSliverHelpers',
  WidgetDjTypes.RenderSliverSingleBoxAdapter: 'RenderSliverSingleBoxAdapter',
  WidgetDjTypes.RenderSliverToBoxAdapter: 'RenderSliverToBoxAdapter',
  WidgetDjTypes.RenderSliverFillViewport: 'RenderSliverFillViewport',
  WidgetDjTypes.RenderSliverFillRemainingWithScrollable:
      'RenderSliverFillRemainingWithScrollable',
  WidgetDjTypes.RenderSliverFillRemaining: 'RenderSliverFillRemaining',
  WidgetDjTypes.RenderSliverFillRemainingAndOverscroll:
      'RenderSliverFillRemainingAndOverscroll',
  WidgetDjTypes.RenderSliverFixedExtentBoxAdaptor:
      'RenderSliverFixedExtentBoxAdaptor',
  WidgetDjTypes.RenderSliverFixedExtentList: 'RenderSliverFixedExtentList',
  WidgetDjTypes.SliverGridGeometry: 'SliverGridGeometry',
  WidgetDjTypes.SliverGridLayout: 'SliverGridLayout',
  WidgetDjTypes.SliverGridRegularTileLayout: 'SliverGridRegularTileLayout',
  WidgetDjTypes.SliverGridDelegate: 'SliverGridDelegate',
  WidgetDjTypes.SliverGridDelegateWithFixedCrossAxisCount:
      'SliverGridDelegateWithFixedCrossAxisCount',
  WidgetDjTypes.SliverGridDelegateWithMaxCrossAxisExtent:
      'SliverGridDelegateWithMaxCrossAxisExtent',
  WidgetDjTypes.SliverGridParentData: 'SliverGridParentData',
  WidgetDjTypes.RenderSliverGrid: 'RenderSliverGrid',
  WidgetDjTypes.RenderSliverList: 'RenderSliverList',
  WidgetDjTypes.RenderSliverBoxChildManager: 'RenderSliverBoxChildManager',
  WidgetDjTypes.SliverMultiBoxAdaptorParentData:
      'SliverMultiBoxAdaptorParentData',
  WidgetDjTypes.RenderSliverEdgeInsetsPadding: 'RenderSliverEdgeInsetsPadding',
  WidgetDjTypes.RenderSliverPadding: 'RenderSliverPadding',
  WidgetDjTypes.OverScrollHeaderStretchConfiguration:
      'OverScrollHeaderStretchConfiguration',
  WidgetDjTypes.PersistentHeaderShowOnScreenConfiguration:
      'PersistentHeaderShowOnScreenConfiguration',
  WidgetDjTypes.RenderSliverPersistentHeader: 'RenderSliverPersistentHeader',
  WidgetDjTypes.RenderSliverScrollingPersistentHeader:
      'RenderSliverScrollingPersistentHeader',
  WidgetDjTypes.RenderSliverPinnedPersistentHeader:
      'RenderSliverPinnedPersistentHeader',
  WidgetDjTypes.FloatingHeaderSnapConfiguration:
      'FloatingHeaderSnapConfiguration',
  WidgetDjTypes.RenderSliverFloatingPersistentHeader:
      'RenderSliverFloatingPersistentHeader',
  WidgetDjTypes.RenderSliverFloatingPinnedPersistentHeader:
      'RenderSliverFloatingPinnedPersistentHeader',
  WidgetDjTypes.RelativeRect: 'RelativeRect',
  WidgetDjTypes.StackParentData: 'StackParentData',
  WidgetDjTypes.RenderIndexedStack: 'RenderIndexedStack',
  WidgetDjTypes.TableCellParentData: 'TableCellParentData',
  WidgetDjTypes.TableColumnWidth: 'TableColumnWidth',
  WidgetDjTypes.IntrinsicColumnWidth: 'IntrinsicColumnWidth',
  WidgetDjTypes.FixedColumnWidth: 'FixedColumnWidth',
  WidgetDjTypes.FractionColumnWidth: 'FractionColumnWidth',
  WidgetDjTypes.FlexColumnWidth: 'FlexColumnWidth',
  WidgetDjTypes.MaxColumnWidth: 'MaxColumnWidth',
  WidgetDjTypes.MinColumnWidth: 'MinColumnWidth',
  WidgetDjTypes.RenderTable: 'RenderTable',
  WidgetDjTypes.TableBorder: 'TableBorder',
  WidgetDjTypes.TextureBox: 'TextureBox',
  WidgetDjTypes.FractionalOffsetTween: 'FractionalOffsetTween',
  WidgetDjTypes.AlignmentTween: 'AlignmentTween',
  WidgetDjTypes.AlignmentGeometryTween: 'AlignmentGeometryTween',
  WidgetDjTypes.ViewConfiguration: 'ViewConfiguration',
  WidgetDjTypes.RenderView: 'RenderView',
  WidgetDjTypes.RenderAbstractViewport: 'RenderAbstractViewport',
  WidgetDjTypes.RevealedOffset: 'RevealedOffset',
  WidgetDjTypes.RenderViewport: 'RenderViewport',
  WidgetDjTypes.RenderShrinkWrappingViewport: 'RenderShrinkWrappingViewport',
  WidgetDjTypes.ViewportOffset: 'ViewportOffset',
  WidgetDjTypes.WrapParentData: 'WrapParentData',
  WidgetDjTypes.Priority: 'Priority',
  WidgetDjTypes.TickerProvider: 'TickerProvider',
  WidgetDjTypes.Ticker: 'Ticker',
  WidgetDjTypes.TickerFuture: 'TickerFuture',
  WidgetDjTypes.TickerCanceled: 'TickerCanceled',
  WidgetDjTypes.SemanticsTag: 'SemanticsTag',
  WidgetDjTypes.CustomSemanticsAction: 'CustomSemanticsAction',
  WidgetDjTypes.SemanticsData: 'SemanticsData',
  WidgetDjTypes.SemanticsHintOverrides: 'SemanticsHintOverrides',
  WidgetDjTypes.SemanticsProperties: 'SemanticsProperties',
  WidgetDjTypes.SemanticsNode: 'SemanticsNode',
  WidgetDjTypes.SemanticsOwner: 'SemanticsOwner',
  WidgetDjTypes.SemanticsConfiguration: 'SemanticsConfiguration',
  WidgetDjTypes.SemanticsSortKey: 'SemanticsSortKey',
  WidgetDjTypes.OrdinalSortKey: 'OrdinalSortKey',
  WidgetDjTypes.SemanticsEvent: 'SemanticsEvent',
  WidgetDjTypes.AnnounceSemanticsEvent: 'AnnounceSemanticsEvent',
  WidgetDjTypes.TooltipSemanticsEvent: 'TooltipSemanticsEvent',
  WidgetDjTypes.LongPressSemanticsEvent: 'LongPressSemanticsEvent',
  WidgetDjTypes.TapSemanticEvent: 'TapSemanticEvent',
  WidgetDjTypes.UpdateLiveRegionEvent: 'UpdateLiveRegionEvent',
  WidgetDjTypes.SemanticsService: 'SemanticsService',
  WidgetDjTypes.AssetBundle: 'AssetBundle',
  WidgetDjTypes.NetworkAssetBundle: 'NetworkAssetBundle',
  WidgetDjTypes.CachingAssetBundle: 'CachingAssetBundle',
  WidgetDjTypes.PlatformAssetBundle: 'PlatformAssetBundle',
  WidgetDjTypes.AutofillHints: 'AutofillHints',
  WidgetDjTypes.AutofillConfiguration: 'AutofillConfiguration',
  WidgetDjTypes.AutofillClient: 'AutofillClient',
  WidgetDjTypes.AutofillScope: 'AutofillScope',
  WidgetDjTypes.BinaryMessenger: 'BinaryMessenger',
  WidgetDjTypes.ClipboardData: 'ClipboardData',
  WidgetDjTypes.Clipboard: 'Clipboard',
  WidgetDjTypes.DeferredComponent: 'DeferredComponent',
  WidgetDjTypes.FontLoader: 'FontLoader',
  WidgetDjTypes.HapticFeedback: 'HapticFeedback',
  WidgetDjTypes.KeyboardKey: 'KeyboardKey',
  WidgetDjTypes.LogicalKeyboardKey: 'LogicalKeyboardKey',
  WidgetDjTypes.PhysicalKeyboardKey: 'PhysicalKeyboardKey',
  WidgetDjTypes.MessageCodec: 'MessageCodec',
  WidgetDjTypes.MethodCall: 'MethodCall',
  WidgetDjTypes.MethodCodec: 'MethodCodec',
  WidgetDjTypes.PlatformException: 'PlatformException',
  WidgetDjTypes.MissingPluginException: 'MissingPluginException',
  WidgetDjTypes.BinaryCodec: 'BinaryCodec',
  WidgetDjTypes.StringCodec: 'StringCodec',
  WidgetDjTypes.JSONMessageCodec: 'JSONMessageCodec',
  WidgetDjTypes.JSONMethodCodec: 'JSONMethodCodec',
  WidgetDjTypes.StandardMessageCodec: 'StandardMessageCodec',
  WidgetDjTypes.StandardMethodCodec: 'StandardMethodCodec',
  WidgetDjTypes.BasicMessageChannel: 'BasicMessageChannel',
  WidgetDjTypes.MethodChannel: 'MethodChannel',
  WidgetDjTypes.OptionalMethodChannel: 'OptionalMethodChannel',
  WidgetDjTypes.EventChannel: 'EventChannel',
  WidgetDjTypes.BinaryMessages: 'BinaryMessages',
  WidgetDjTypes.PlatformViewsRegistry: 'PlatformViewsRegistry',
  WidgetDjTypes.PlatformViewsService: 'PlatformViewsService',
  WidgetDjTypes.AndroidPointerProperties: 'AndroidPointerProperties',
  WidgetDjTypes.AndroidPointerCoords: 'AndroidPointerCoords',
  WidgetDjTypes.AndroidMotionEvent: 'AndroidMotionEvent',
  WidgetDjTypes.AndroidViewController: 'AndroidViewController',
  WidgetDjTypes.SurfaceAndroidViewController: 'SurfaceAndroidViewController',
  WidgetDjTypes.TextureAndroidViewController: 'TextureAndroidViewController',
  WidgetDjTypes.UiKitViewController: 'UiKitViewController',
  WidgetDjTypes.PlatformViewController: 'PlatformViewController',
  WidgetDjTypes.RawKeyEventData: 'RawKeyEventData',
  WidgetDjTypes.RawKeyEvent: 'RawKeyEvent',
  WidgetDjTypes.RawKeyDownEvent: 'RawKeyDownEvent',
  WidgetDjTypes.RawKeyUpEvent: 'RawKeyUpEvent',
  WidgetDjTypes.RawKeyboard: 'RawKeyboard',
  WidgetDjTypes.RawKeyEventDataAndroid: 'RawKeyEventDataAndroid',
  WidgetDjTypes.RawKeyEventDataFuchsia: 'RawKeyEventDataFuchsia',
  WidgetDjTypes.RawKeyEventDataIos: 'RawKeyEventDataIos',
  WidgetDjTypes.RawKeyEventDataLinux: 'RawKeyEventDataLinux',
  WidgetDjTypes.KeyHelper: 'KeyHelper',
  WidgetDjTypes.GLFWKeyHelper: 'GLFWKeyHelper',
  WidgetDjTypes.GtkKeyHelper: 'GtkKeyHelper',
  WidgetDjTypes.RawKeyEventDataMacOs: 'RawKeyEventDataMacOs',
  WidgetDjTypes.RawKeyEventDataWeb: 'RawKeyEventDataWeb',
  WidgetDjTypes.RawKeyEventDataWindows: 'RawKeyEventDataWindows',
  WidgetDjTypes.RestorationManager: 'RestorationManager',
  WidgetDjTypes.RestorationBucket: 'RestorationBucket',
  WidgetDjTypes.SystemChannels: 'SystemChannels',
  WidgetDjTypes.ApplicationSwitcherDescription:
      'ApplicationSwitcherDescription',
  WidgetDjTypes.SystemUiOverlayStyle: 'SystemUiOverlayStyle',
  WidgetDjTypes.SystemChrome: 'SystemChrome',
  WidgetDjTypes.SystemNavigator: 'SystemNavigator',
  WidgetDjTypes.SystemSound: 'SystemSound',
  WidgetDjTypes.TextSelection: 'TextSelection',
  WidgetDjTypes.TextInputFormatter: 'TextInputFormatter',
  WidgetDjTypes.FilteringTextInputFormatter: 'FilteringTextInputFormatter',
  WidgetDjTypes.BlacklistingTextInputFormatter:
      'BlacklistingTextInputFormatter',
  WidgetDjTypes.WhitelistingTextInputFormatter:
      'WhitelistingTextInputFormatter',
  WidgetDjTypes.LengthLimitingTextInputFormatter:
      'LengthLimitingTextInputFormatter',
  WidgetDjTypes.TextInputType: 'TextInputType',
  WidgetDjTypes.TextInputConfiguration: 'TextInputConfiguration',
  WidgetDjTypes.RawFloatingCursorPoint: 'RawFloatingCursorPoint',
  WidgetDjTypes.TextEditingValue: 'TextEditingValue',
  WidgetDjTypes.TextSelectionDelegate: 'TextSelectionDelegate',
  WidgetDjTypes.TextInputClient: 'TextInputClient',
  WidgetDjTypes.TextInputConnection: 'TextInputConnection',
  WidgetDjTypes.TextInput: 'TextInput',
  WidgetDjTypes.Intent: 'Intent',
  WidgetDjTypes.Action: 'Action',
  WidgetDjTypes.ActionListener: 'ActionListener',
  WidgetDjTypes.ContextAction: 'ContextAction',
  WidgetDjTypes.CallbackAction: 'CallbackAction',
  WidgetDjTypes.ActionDispatcher: 'ActionDispatcher',
  WidgetDjTypes.Actions: 'Actions',
  WidgetDjTypes.FocusableActionDetector: 'FocusableActionDetector',
  WidgetDjTypes.DoNothingIntent: 'DoNothingIntent',
  WidgetDjTypes.DoNothingAndStopPropagationIntent:
      'DoNothingAndStopPropagationIntent',
  WidgetDjTypes.DoNothingAction: 'DoNothingAction',
  WidgetDjTypes.ActivateIntent: 'ActivateIntent',
  WidgetDjTypes.ButtonActivateIntent: 'ButtonActivateIntent',
  WidgetDjTypes.ActivateAction: 'ActivateAction',
  WidgetDjTypes.SelectAction: 'SelectAction',
  WidgetDjTypes.DismissAction: 'DismissAction',
  WidgetDjTypes.PrioritizedAction: 'PrioritizedAction',
  WidgetDjTypes.AnimatedCrossFade: 'AnimatedCrossFade',
  WidgetDjTypes.AnimatedList: 'AnimatedList',
  WidgetDjTypes.AnimatedListState: 'AnimatedListState',
  WidgetDjTypes.SliverAnimatedList: 'SliverAnimatedList',
  WidgetDjTypes.SliverAnimatedListState: 'SliverAnimatedListState',
  WidgetDjTypes.AnimatedSize: 'AnimatedSize',
  WidgetDjTypes.AnimatedSwitcher: 'AnimatedSwitcher',
  WidgetDjTypes.AnnotatedRegion: 'AnnotatedRegion',
  WidgetDjTypes.WidgetsApp: 'WidgetsApp',
  WidgetDjTypes.StreamBuilderBase: 'StreamBuilderBase',
  WidgetDjTypes.AsyncSnapshot: 'AsyncSnapshot',
  WidgetDjTypes.StreamBuilder: 'StreamBuilder',
  WidgetDjTypes.FutureBuilder: 'FutureBuilder',
  WidgetDjTypes.RawAutocomplete: 'RawAutocomplete',
  WidgetDjTypes.AutofillGroup: 'AutofillGroup',
  WidgetDjTypes.AutofillGroupState: 'AutofillGroupState',
  WidgetDjTypes.AutomaticKeepAlive: 'AutomaticKeepAlive',
  WidgetDjTypes.KeepAliveNotification: 'KeepAliveNotification',
  WidgetDjTypes.KeepAliveHandle: 'KeepAliveHandle',
  WidgetDjTypes.BannerPainter: 'BannerPainter',
  WidgetDjTypes.Banner: 'Banner',
  WidgetDjTypes.CheckedModeBanner: 'CheckedModeBanner',
  WidgetDjTypes.Directionality: 'Directionality',
  WidgetDjTypes.Opacity: 'Opacity',
  WidgetDjTypes.ShaderMask: 'ShaderMask',
  WidgetDjTypes.BackdropFilter: 'BackdropFilter',
  WidgetDjTypes.CustomPaint: 'CustomPaint',
  WidgetDjTypes.ClipRect: 'ClipRect',
  WidgetDjTypes.ClipRRect: 'ClipRRect',
  WidgetDjTypes.ClipOval: 'ClipOval',
  WidgetDjTypes.ClipPath: 'ClipPath',
  WidgetDjTypes.PhysicalModel: 'PhysicalModel',
  WidgetDjTypes.PhysicalShape: 'PhysicalShape',
  WidgetDjTypes.Transform: 'Transform',
  WidgetDjTypes.CompositedTransformTarget: 'CompositedTransformTarget',
  WidgetDjTypes.CompositedTransformFollower: 'CompositedTransformFollower',
  WidgetDjTypes.FittedBox: 'FittedBox',
  WidgetDjTypes.FractionalTranslation: 'FractionalTranslation',
  WidgetDjTypes.RotatedBox: 'RotatedBox',
  WidgetDjTypes.Padding: 'Padding',
  WidgetDjTypes.Align: 'Align',
  WidgetDjTypes.Center: 'Center',
  WidgetDjTypes.CustomSingleChildLayout: 'CustomSingleChildLayout',
  WidgetDjTypes.LayoutId: 'LayoutId',
  WidgetDjTypes.CustomMultiChildLayout: 'CustomMultiChildLayout',
  WidgetDjTypes.SizedBox: 'SizedBox',
  WidgetDjTypes.ConstrainedBox: 'ConstrainedBox',
  WidgetDjTypes.UnconstrainedBox: 'UnconstrainedBox',
  WidgetDjTypes.FractionallySizedBox: 'FractionallySizedBox',
  WidgetDjTypes.LimitedBox: 'LimitedBox',
  WidgetDjTypes.OverflowBox: 'OverflowBox',
  WidgetDjTypes.SizedOverflowBox: 'SizedOverflowBox',
  WidgetDjTypes.Offstage: 'Offstage',
  WidgetDjTypes.AspectRatio: 'AspectRatio',
  WidgetDjTypes.IntrinsicWidth: 'IntrinsicWidth',
  WidgetDjTypes.IntrinsicHeight: 'IntrinsicHeight',
  WidgetDjTypes.Baseline: 'Baseline',
  WidgetDjTypes.SliverToBoxAdapter: 'SliverToBoxAdapter',
  WidgetDjTypes.SliverPadding: 'SliverPadding',
  WidgetDjTypes.ListBody: 'ListBody',
  WidgetDjTypes.Stack: 'Stack',
  WidgetDjTypes.IndexedStack: 'IndexedStack',
  WidgetDjTypes.Positioned: 'Positioned',
  WidgetDjTypes.PositionedDirectional: 'PositionedDirectional',
  WidgetDjTypes.Flex: 'Flex',
  WidgetDjTypes.Row: 'Row',
  WidgetDjTypes.Column: 'Column',
  WidgetDjTypes.Flexible: 'Flexible',
  WidgetDjTypes.Expanded: 'Expanded',
  WidgetDjTypes.Wrap: 'Wrap',
  WidgetDjTypes.Flow: 'Flow',
  WidgetDjTypes.RichText: 'RichText',
  WidgetDjTypes.RawImage: 'RawImage',
  WidgetDjTypes.DefaultAssetBundle: 'DefaultAssetBundle',
  WidgetDjTypes.WidgetToRenderBoxAdapter: 'WidgetToRenderBoxAdapter',
  WidgetDjTypes.Listener: 'Listener',
  WidgetDjTypes.MouseRegion: 'MouseRegion',
  WidgetDjTypes.RepaintBoundary: 'RepaintBoundary',
  WidgetDjTypes.IgnorePointer: 'IgnorePointer',
  WidgetDjTypes.AbsorbPointer: 'AbsorbPointer',
  WidgetDjTypes.MetaData: 'MetaData',
  WidgetDjTypes.Semantics: 'Semantics',
  WidgetDjTypes.MergeSemantics: 'MergeSemantics',
  WidgetDjTypes.BlockSemantics: 'BlockSemantics',
  WidgetDjTypes.ExcludeSemantics: 'ExcludeSemantics',
  WidgetDjTypes.IndexedSemantics: 'IndexedSemantics',
  WidgetDjTypes.KeyedSubtree: 'KeyedSubtree',
  WidgetDjTypes.Builder: 'Builder',
  WidgetDjTypes.StatefulBuilder: 'StatefulBuilder',
  WidgetDjTypes.ColoredBox: 'ColoredBox',
  WidgetDjTypes.WidgetsBindingObserver: 'WidgetsBindingObserver',
  WidgetDjTypes.RenderObjectToWidgetAdapter: 'RenderObjectToWidgetAdapter',
  WidgetDjTypes.RenderObjectToWidgetElement: 'RenderObjectToWidgetElement',
  WidgetDjTypes.WidgetsFlutterBinding: 'WidgetsFlutterBinding',
  WidgetDjTypes.BottomNavigationBarItem: 'BottomNavigationBarItem',
  WidgetDjTypes.ColorFiltered: 'ColorFiltered',
  WidgetDjTypes.DecoratedBox: 'DecoratedBox',
  WidgetDjTypes.Container: 'Container',
  WidgetDjTypes.DesktopTextSelectionToolbarLayoutDelegate:
      'DesktopTextSelectionToolbarLayoutDelegate',
  WidgetDjTypes.Dismissible: 'Dismissible',
  WidgetDjTypes.DisposableBuildContext: 'DisposableBuildContext',
  WidgetDjTypes.DraggableScrollableSheet: 'DraggableScrollableSheet',
  WidgetDjTypes.DraggableScrollableNotification:
      'DraggableScrollableNotification',
  WidgetDjTypes.DraggableScrollableActuator: 'DraggableScrollableActuator',
  WidgetDjTypes.Draggable: 'Draggable',
  WidgetDjTypes.LongPressDraggable: 'LongPressDraggable',
  WidgetDjTypes.DraggableDetails: 'DraggableDetails',
  WidgetDjTypes.DragTargetDetails: 'DragTargetDetails',
  WidgetDjTypes.DragTarget: 'DragTarget',
  WidgetDjTypes.DualTransitionBuilder: 'DualTransitionBuilder',
  WidgetDjTypes.TextEditingController: 'TextEditingController',
  WidgetDjTypes.ToolbarOptions: 'ToolbarOptions',
  WidgetDjTypes.EditableText: 'EditableText',
  WidgetDjTypes.EditableTextState: 'EditableTextState',
  WidgetDjTypes.FadeInImage: 'FadeInImage',
  WidgetDjTypes.FocusAttachment: 'FocusAttachment',
  WidgetDjTypes.FocusNode: 'FocusNode',
  WidgetDjTypes.FocusScopeNode: 'FocusScopeNode',
  WidgetDjTypes.FocusManager: 'FocusManager',
  WidgetDjTypes.Focus: 'Focus',
  WidgetDjTypes.FocusScope: 'FocusScope',
  WidgetDjTypes.ExcludeFocus: 'ExcludeFocus',
  WidgetDjTypes.FocusTraversalPolicy: 'FocusTraversalPolicy',
  WidgetDjTypes.NumericFocusOrder: 'NumericFocusOrder',
  WidgetDjTypes.LexicalFocusOrder: 'LexicalFocusOrder',
  WidgetDjTypes.FocusTraversalOrder: 'FocusTraversalOrder',
  WidgetDjTypes.FocusTraversalGroup: 'FocusTraversalGroup',
  WidgetDjTypes.RequestFocusIntent: 'RequestFocusIntent',
  WidgetDjTypes.RequestFocusAction: 'RequestFocusAction',
  WidgetDjTypes.NextFocusIntent: 'NextFocusIntent',
  WidgetDjTypes.NextFocusAction: 'NextFocusAction',
  WidgetDjTypes.PreviousFocusIntent: 'PreviousFocusIntent',
  WidgetDjTypes.PreviousFocusAction: 'PreviousFocusAction',
  WidgetDjTypes.DirectionalFocusIntent: 'DirectionalFocusIntent',
  WidgetDjTypes.DirectionalFocusAction: 'DirectionalFocusAction',
  WidgetDjTypes.Form: 'Form',
  WidgetDjTypes.FormState: 'FormState',
  WidgetDjTypes.FormField: 'FormField',
  WidgetDjTypes.FormFieldState: 'FormFieldState',
  WidgetDjTypes.UniqueKey: 'UniqueKey',
  WidgetDjTypes.ObjectKey: 'ObjectKey',
  WidgetDjTypes.GlobalKey: 'GlobalKey',
  WidgetDjTypes.LabeledGlobalKey: 'LabeledGlobalKey',
  WidgetDjTypes.GlobalObjectKey: 'GlobalObjectKey',
  WidgetDjTypes.TypeMatcher: 'TypeMatcher',
  WidgetDjTypes.Widget: 'Widget',
  WidgetDjTypes.StatelessWidget: 'StatelessWidget',
  WidgetDjTypes.StatefulWidget: 'StatefulWidget',
  WidgetDjTypes.State: 'State',
  WidgetDjTypes.ProxyWidget: 'ProxyWidget',
  WidgetDjTypes.ParentDataWidget: 'ParentDataWidget',
  WidgetDjTypes.InheritedWidget: 'InheritedWidget',
  WidgetDjTypes.RenderObjectWidget: 'RenderObjectWidget',
  WidgetDjTypes.LeafRenderObjectWidget: 'LeafRenderObjectWidget',
  WidgetDjTypes.SingleChildRenderObjectWidget: 'SingleChildRenderObjectWidget',
  WidgetDjTypes.MultiChildRenderObjectWidget: 'MultiChildRenderObjectWidget',
  WidgetDjTypes.BuildContext: 'BuildContext',
  WidgetDjTypes.BuildOwner: 'BuildOwner',
  WidgetDjTypes.Element: 'Element',
  WidgetDjTypes.ErrorWidget: 'ErrorWidget',
  WidgetDjTypes.ComponentElement: 'ComponentElement',
  WidgetDjTypes.StatelessElement: 'StatelessElement',
  WidgetDjTypes.StatefulElement: 'StatefulElement',
  WidgetDjTypes.ProxyElement: 'ProxyElement',
  WidgetDjTypes.ParentDataElement: 'ParentDataElement',
  WidgetDjTypes.InheritedElement: 'InheritedElement',
  WidgetDjTypes.RenderObjectElement: 'RenderObjectElement',
  WidgetDjTypes.RootRenderObjectElement: 'RootRenderObjectElement',
  WidgetDjTypes.LeafRenderObjectElement: 'LeafRenderObjectElement',
  WidgetDjTypes.SingleChildRenderObjectElement:
      'SingleChildRenderObjectElement',
  WidgetDjTypes.MultiChildRenderObjectElement: 'MultiChildRenderObjectElement',
  WidgetDjTypes.DebugCreator: 'DebugCreator',
  WidgetDjTypes.IndexedSlot: 'IndexedSlot',
  WidgetDjTypes.GestureRecognizerFactory: 'GestureRecognizerFactory',
  WidgetDjTypes.GestureRecognizerFactoryWithHandlers:
      'GestureRecognizerFactoryWithHandlers',
  WidgetDjTypes.GestureDetector: 'GestureDetector',
  WidgetDjTypes.RawGestureDetector: 'RawGestureDetector',
  WidgetDjTypes.RawGestureDetectorState: 'RawGestureDetectorState',
  WidgetDjTypes.SemanticsGestureDelegate: 'SemanticsGestureDelegate',
  WidgetDjTypes.GridPaper: 'GridPaper',
  WidgetDjTypes.Hero: 'Hero',
  WidgetDjTypes.HeroController: 'HeroController',
  WidgetDjTypes.HeroMode: 'HeroMode',
  WidgetDjTypes.Icon: 'Icon',
  WidgetDjTypes.IconData: 'IconData',
  WidgetDjTypes.IconDataProperty: 'IconDataProperty',
  WidgetDjTypes.IconTheme: 'IconTheme',
  WidgetDjTypes.IconThemeData: 'IconThemeData',
  WidgetDjTypes.Image: 'Image',
  WidgetDjTypes.ImageFiltered: 'ImageFiltered',
  WidgetDjTypes.ImageIcon: 'ImageIcon',
  WidgetDjTypes.BoxConstraintsTween: 'BoxConstraintsTween',
  WidgetDjTypes.DecorationTween: 'DecorationTween',
  WidgetDjTypes.EdgeInsetsTween: 'EdgeInsetsTween',
  WidgetDjTypes.EdgeInsetsGeometryTween: 'EdgeInsetsGeometryTween',
  WidgetDjTypes.BorderRadiusTween: 'BorderRadiusTween',
  WidgetDjTypes.BorderTween: 'BorderTween',
  WidgetDjTypes.Matrix4Tween: 'Matrix4Tween',
  WidgetDjTypes.TextStyleTween: 'TextStyleTween',
  WidgetDjTypes.ImplicitlyAnimatedWidget: 'ImplicitlyAnimatedWidget',
  WidgetDjTypes.ImplicitlyAnimatedWidgetState: 'ImplicitlyAnimatedWidgetState',
  WidgetDjTypes.AnimatedWidgetBaseState: 'AnimatedWidgetBaseState',
  WidgetDjTypes.AnimatedContainer: 'AnimatedContainer',
  WidgetDjTypes.AnimatedPadding: 'AnimatedPadding',
  WidgetDjTypes.AnimatedAlign: 'AnimatedAlign',
  WidgetDjTypes.AnimatedPositioned: 'AnimatedPositioned',
  WidgetDjTypes.AnimatedPositionedDirectional: 'AnimatedPositionedDirectional',
  WidgetDjTypes.AnimatedOpacity: 'AnimatedOpacity',
  WidgetDjTypes.SliverAnimatedOpacity: 'SliverAnimatedOpacity',
  WidgetDjTypes.AnimatedDefaultTextStyle: 'AnimatedDefaultTextStyle',
  WidgetDjTypes.AnimatedPhysicalModel: 'AnimatedPhysicalModel',
  WidgetDjTypes.InheritedModel: 'InheritedModel',
  WidgetDjTypes.InheritedModelElement: 'InheritedModelElement',
  WidgetDjTypes.InheritedNotifier: 'InheritedNotifier',
  WidgetDjTypes.InheritedTheme: 'InheritedTheme',
  WidgetDjTypes.CapturedThemes: 'CapturedThemes',
  WidgetDjTypes.InteractiveViewer: 'InteractiveViewer',
  WidgetDjTypes.TransformationController: 'TransformationController',
  WidgetDjTypes.ConstrainedLayoutBuilder: 'ConstrainedLayoutBuilder',
  WidgetDjTypes.LayoutBuilder: 'LayoutBuilder',
  WidgetDjTypes.ListWheelChildDelegate: 'ListWheelChildDelegate',
  WidgetDjTypes.ListWheelChildListDelegate: 'ListWheelChildListDelegate',
  WidgetDjTypes.ListWheelChildLoopingListDelegate:
      'ListWheelChildLoopingListDelegate',
  WidgetDjTypes.ListWheelChildBuilderDelegate: 'ListWheelChildBuilderDelegate',
  WidgetDjTypes.FixedExtentScrollController: 'FixedExtentScrollController',
  WidgetDjTypes.FixedExtentMetrics: 'FixedExtentMetrics',
  WidgetDjTypes.FixedExtentScrollPhysics: 'FixedExtentScrollPhysics',
  WidgetDjTypes.ListWheelScrollView: 'ListWheelScrollView',
  WidgetDjTypes.ListWheelElement: 'ListWheelElement',
  WidgetDjTypes.ListWheelViewport: 'ListWheelViewport',
  WidgetDjTypes.LocalizationsDelegate: 'LocalizationsDelegate',
  WidgetDjTypes.WidgetsLocalizations: 'WidgetsLocalizations',
  WidgetDjTypes.DefaultWidgetsLocalizations: 'DefaultWidgetsLocalizations',
  WidgetDjTypes.Localizations: 'Localizations',
  WidgetDjTypes.MediaQueryData: 'MediaQueryData',
  WidgetDjTypes.MediaQuery: 'MediaQuery',
  WidgetDjTypes.ModalBarrier: 'ModalBarrier',
  WidgetDjTypes.AnimatedModalBarrier: 'AnimatedModalBarrier',
  WidgetDjTypes.NavigationToolbar: 'NavigationToolbar',
  WidgetDjTypes.Route: 'Route',
  WidgetDjTypes.RouteSettings: 'RouteSettings',
  WidgetDjTypes.Page: 'Page',
  WidgetDjTypes.NavigatorObserver: 'NavigatorObserver',
  WidgetDjTypes.HeroControllerScope: 'HeroControllerScope',
  WidgetDjTypes.RouteTransitionRecord: 'RouteTransitionRecord',
  WidgetDjTypes.TransitionDelegate: 'TransitionDelegate',
  WidgetDjTypes.DefaultTransitionDelegate: 'DefaultTransitionDelegate',
  WidgetDjTypes.Navigator: 'Navigator',
  WidgetDjTypes.NavigatorState: 'NavigatorState',
  WidgetDjTypes.RestorableRouteFuture: 'RestorableRouteFuture',
  WidgetDjTypes.NestedScrollView: 'NestedScrollView',
  WidgetDjTypes.NestedScrollViewState: 'NestedScrollViewState',
  WidgetDjTypes.SliverOverlapAbsorberHandle: 'SliverOverlapAbsorberHandle',
  WidgetDjTypes.SliverOverlapAbsorber: 'SliverOverlapAbsorber',
  WidgetDjTypes.RenderSliverOverlapAbsorber: 'RenderSliverOverlapAbsorber',
  WidgetDjTypes.SliverOverlapInjector: 'SliverOverlapInjector',
  WidgetDjTypes.RenderSliverOverlapInjector: 'RenderSliverOverlapInjector',
  WidgetDjTypes.NestedScrollViewViewport: 'NestedScrollViewViewport',
  WidgetDjTypes.RenderNestedScrollViewViewport:
      'RenderNestedScrollViewViewport',
  WidgetDjTypes.Notification: 'Notification',
  WidgetDjTypes.NotificationListener: 'NotificationListener',
  WidgetDjTypes.OrientationBuilder: 'OrientationBuilder',
  WidgetDjTypes.OverflowBar: 'OverflowBar',
  WidgetDjTypes.OverlayEntry: 'OverlayEntry',
  WidgetDjTypes.Overlay: 'Overlay',
  WidgetDjTypes.OverlayState: 'OverlayState',
  WidgetDjTypes.GlowingOverscrollIndicator: 'GlowingOverscrollIndicator',
  WidgetDjTypes.OverscrollIndicatorNotification:
      'OverscrollIndicatorNotification',
  WidgetDjTypes.PageRoute: 'PageRoute',
  WidgetDjTypes.PageRouteBuilder: 'PageRouteBuilder',
  WidgetDjTypes.PageStorageKey: 'PageStorageKey',
  WidgetDjTypes.PageStorageBucket: 'PageStorageBucket',
  WidgetDjTypes.PageStorage: 'PageStorage',
  WidgetDjTypes.PageController: 'PageController',
  WidgetDjTypes.PageMetrics: 'PageMetrics',
  WidgetDjTypes.PageScrollPhysics: 'PageScrollPhysics',
  WidgetDjTypes.PageView: 'PageView',
  WidgetDjTypes.PerformanceOverlay: 'PerformanceOverlay',
  WidgetDjTypes.Placeholder: 'Placeholder',
  WidgetDjTypes.AndroidView: 'AndroidView',
  WidgetDjTypes.UiKitView: 'UiKitView',
  WidgetDjTypes.HtmlElementView: 'HtmlElementView',
  WidgetDjTypes.PlatformViewCreationParams: 'PlatformViewCreationParams',
  WidgetDjTypes.PlatformViewLink: 'PlatformViewLink',
  WidgetDjTypes.PlatformViewSurface: 'PlatformViewSurface',
  WidgetDjTypes.AndroidViewSurface: 'AndroidViewSurface',
  WidgetDjTypes.PreferredSizeWidget: 'PreferredSizeWidget',
  WidgetDjTypes.PreferredSize: 'PreferredSize',
  WidgetDjTypes.PrimaryScrollController: 'PrimaryScrollController',
  WidgetDjTypes.RawKeyboardListener: 'RawKeyboardListener',
  WidgetDjTypes.ReorderableList: 'ReorderableList',
  WidgetDjTypes.ReorderableListState: 'ReorderableListState',
  WidgetDjTypes.SliverReorderableList: 'SliverReorderableList',
  WidgetDjTypes.SliverReorderableListState: 'SliverReorderableListState',
  WidgetDjTypes.ReorderableDragStartListener: 'ReorderableDragStartListener',
  WidgetDjTypes.ReorderableDelayedDragStartListener:
      'ReorderableDelayedDragStartListener',
  WidgetDjTypes.RestorationScope: 'RestorationScope',
  WidgetDjTypes.UnmanagedRestorationScope: 'UnmanagedRestorationScope',
  WidgetDjTypes.RootRestorationScope: 'RootRestorationScope',
  WidgetDjTypes.RestorableProperty: 'RestorableProperty',
  WidgetDjTypes.RestorableValue: 'RestorableValue',
  WidgetDjTypes.RestorableNum: 'RestorableNum',
  WidgetDjTypes.RestorableDouble: 'RestorableDouble',
  WidgetDjTypes.RestorableInt: 'RestorableInt',
  WidgetDjTypes.RestorableString: 'RestorableString',
  WidgetDjTypes.RestorableBool: 'RestorableBool',
  WidgetDjTypes.RestorableBoolN: 'RestorableBoolN',
  WidgetDjTypes.RestorableNumN: 'RestorableNumN',
  WidgetDjTypes.RestorableDoubleN: 'RestorableDoubleN',
  WidgetDjTypes.RestorableIntN: 'RestorableIntN',
  WidgetDjTypes.RestorableStringN: 'RestorableStringN',
  WidgetDjTypes.RestorableListenable: 'RestorableListenable',
  WidgetDjTypes.RestorableChangeNotifier: 'RestorableChangeNotifier',
  WidgetDjTypes.RestorableTextEditingController:
      'RestorableTextEditingController',
  WidgetDjTypes.RouteInformation: 'RouteInformation',
  WidgetDjTypes.Router: 'Router',
  WidgetDjTypes.BackButtonDispatcher: 'BackButtonDispatcher',
  WidgetDjTypes.RootBackButtonDispatcher: 'RootBackButtonDispatcher',
  WidgetDjTypes.ChildBackButtonDispatcher: 'ChildBackButtonDispatcher',
  WidgetDjTypes.RouteInformationParser: 'RouteInformationParser',
  WidgetDjTypes.RouterDelegate: 'RouterDelegate',
  WidgetDjTypes.RouteInformationProvider: 'RouteInformationProvider',
  WidgetDjTypes.PlatformRouteInformationProvider:
      'PlatformRouteInformationProvider',
  WidgetDjTypes.OverlayRoute: 'OverlayRoute',
  WidgetDjTypes.TransitionRoute: 'TransitionRoute',
  WidgetDjTypes.LocalHistoryEntry: 'LocalHistoryEntry',
  WidgetDjTypes.ModalRoute: 'ModalRoute',
  WidgetDjTypes.PopupRoute: 'PopupRoute',
  WidgetDjTypes.RouteObserver: 'RouteObserver',
  WidgetDjTypes.RouteAware: 'RouteAware',
  WidgetDjTypes.RawDialogRoute: 'RawDialogRoute',
  WidgetDjTypes.SafeArea: 'SafeArea',
  WidgetDjTypes.SliverSafeArea: 'SliverSafeArea',
  WidgetDjTypes.Scrollable: 'Scrollable',
  WidgetDjTypes.ScrollIncrementDetails: 'ScrollIncrementDetails',
  WidgetDjTypes.ScrollIntent: 'ScrollIntent',
  WidgetDjTypes.ScrollAction: 'ScrollAction',
  WidgetDjTypes.ScrollbarPainter: 'ScrollbarPainter',
  WidgetDjTypes.RawScrollbar: 'RawScrollbar',
  WidgetDjTypes.RawScrollbarState: 'RawScrollbarState',
  WidgetDjTypes.ScrollActivityDelegate: 'ScrollActivityDelegate',
  WidgetDjTypes.ScrollActivity: 'ScrollActivity',
  WidgetDjTypes.IdleScrollActivity: 'IdleScrollActivity',
  WidgetDjTypes.ScrollHoldController: 'ScrollHoldController',
  WidgetDjTypes.HoldScrollActivity: 'HoldScrollActivity',
  WidgetDjTypes.ScrollDragController: 'ScrollDragController',
  WidgetDjTypes.DragScrollActivity: 'DragScrollActivity',
  WidgetDjTypes.BallisticScrollActivity: 'BallisticScrollActivity',
  WidgetDjTypes.DrivenScrollActivity: 'DrivenScrollActivity',
  WidgetDjTypes.ScrollAwareImageProvider: 'ScrollAwareImageProvider',
  WidgetDjTypes.ScrollBehavior: 'ScrollBehavior',
  WidgetDjTypes.ScrollConfiguration: 'ScrollConfiguration',
  WidgetDjTypes.ScrollContext: 'ScrollContext',
  WidgetDjTypes.ScrollController: 'ScrollController',
  WidgetDjTypes.TrackingScrollController: 'TrackingScrollController',
  WidgetDjTypes.ScrollMetrics: 'ScrollMetrics',
  WidgetDjTypes.FixedScrollMetrics: 'FixedScrollMetrics',
  WidgetDjTypes.ScrollNotification: 'ScrollNotification',
  WidgetDjTypes.ScrollStartNotification: 'ScrollStartNotification',
  WidgetDjTypes.ScrollUpdateNotification: 'ScrollUpdateNotification',
  WidgetDjTypes.OverscrollNotification: 'OverscrollNotification',
  WidgetDjTypes.ScrollEndNotification: 'ScrollEndNotification',
  WidgetDjTypes.UserScrollNotification: 'UserScrollNotification',
  WidgetDjTypes.ScrollPhysics: 'ScrollPhysics',
  WidgetDjTypes.RangeMaintainingScrollPhysics: 'RangeMaintainingScrollPhysics',
  WidgetDjTypes.BouncingScrollPhysics: 'BouncingScrollPhysics',
  WidgetDjTypes.ClampingScrollPhysics: 'ClampingScrollPhysics',
  WidgetDjTypes.AlwaysScrollableScrollPhysics: 'AlwaysScrollableScrollPhysics',
  WidgetDjTypes.NeverScrollableScrollPhysics: 'NeverScrollableScrollPhysics',
  WidgetDjTypes.ScrollPosition: 'ScrollPosition',
  WidgetDjTypes.ScrollPositionWithSingleContext:
      'ScrollPositionWithSingleContext',
  WidgetDjTypes.BouncingScrollSimulation: 'BouncingScrollSimulation',
  WidgetDjTypes.ClampingScrollSimulation: 'ClampingScrollSimulation',
  WidgetDjTypes.ScrollView: 'ScrollView',
  WidgetDjTypes.CustomScrollView: 'CustomScrollView',
  WidgetDjTypes.BoxScrollView: 'BoxScrollView',
  WidgetDjTypes.ListView: 'ListView',
  WidgetDjTypes.GridView: 'GridView',
  WidgetDjTypes.SemanticsDebugger: 'SemanticsDebugger',
  WidgetDjTypes.KeySet: 'KeySet',
  WidgetDjTypes.LogicalKeySet: 'LogicalKeySet',
  WidgetDjTypes.ShortcutMapProperty: 'ShortcutMapProperty',
  WidgetDjTypes.ShortcutManager: 'ShortcutManager',
  WidgetDjTypes.Shortcuts: 'Shortcuts',
  WidgetDjTypes.SingleChildScrollView: 'SingleChildScrollView',
  WidgetDjTypes.SizeChangedLayoutNotification: 'SizeChangedLayoutNotification',
  WidgetDjTypes.SliverChildDelegate: 'SliverChildDelegate',
  WidgetDjTypes.SliverChildBuilderDelegate: 'SliverChildBuilderDelegate',
  WidgetDjTypes.SliverChildListDelegate: 'SliverChildListDelegate',
  WidgetDjTypes.SliverWithKeepAliveWidget: 'SliverWithKeepAliveWidget',
  WidgetDjTypes.SliverMultiBoxAdaptorWidget: 'SliverMultiBoxAdaptorWidget',
  WidgetDjTypes.SliverList: 'SliverList',
  WidgetDjTypes.SliverFixedExtentList: 'SliverFixedExtentList',
  WidgetDjTypes.SliverGrid: 'SliverGrid',
  WidgetDjTypes.SliverMultiBoxAdaptorElement: 'SliverMultiBoxAdaptorElement',
  WidgetDjTypes.SliverOpacity: 'SliverOpacity',
  WidgetDjTypes.SliverIgnorePointer: 'SliverIgnorePointer',
  WidgetDjTypes.SliverOffstage: 'SliverOffstage',
  WidgetDjTypes.KeepAlive: 'KeepAlive',
  WidgetDjTypes.SliverFillViewport: 'SliverFillViewport',
  WidgetDjTypes.SliverFillRemaining: 'SliverFillRemaining',
  WidgetDjTypes.SliverLayoutBuilder: 'SliverLayoutBuilder',
  WidgetDjTypes.SliverPersistentHeaderDelegate:
      'SliverPersistentHeaderDelegate',
  WidgetDjTypes.SliverPersistentHeader: 'SliverPersistentHeader',
  WidgetDjTypes.SliverPrototypeExtentList: 'SliverPrototypeExtentList',
  WidgetDjTypes.Spacer: 'Spacer',
  WidgetDjTypes.StatusTransitionWidget: 'StatusTransitionWidget',
  WidgetDjTypes.TableRow: 'TableRow',
  WidgetDjTypes.Table: 'Table',
  WidgetDjTypes.TableCell: 'TableCell',
  WidgetDjTypes.DefaultTextStyle: 'DefaultTextStyle',
  WidgetDjTypes.DefaultTextHeightBehavior: 'DefaultTextHeightBehavior',
  WidgetDjTypes.Text: 'Text',
  WidgetDjTypes.Texture: 'Texture',
  WidgetDjTypes.ToolbarItemsParentData: 'ToolbarItemsParentData',
  WidgetDjTypes.TextSelectionControls: 'TextSelectionControls',
  WidgetDjTypes.TextSelectionOverlay: 'TextSelectionOverlay',
  WidgetDjTypes.TextSelectionGestureDetectorBuilderDelegate:
      'TextSelectionGestureDetectorBuilderDelegate',
  WidgetDjTypes.TextSelectionGestureDetectorBuilder:
      'TextSelectionGestureDetectorBuilder',
  WidgetDjTypes.TextSelectionGestureDetector: 'TextSelectionGestureDetector',
  WidgetDjTypes.ClipboardStatusNotifier: 'ClipboardStatusNotifier',
  WidgetDjTypes.TextSelectionToolbarLayoutDelegate:
      'TextSelectionToolbarLayoutDelegate',
  WidgetDjTypes.TickerMode: 'TickerMode',
  WidgetDjTypes.Title: 'Title',
  WidgetDjTypes.AnimatedWidget: 'AnimatedWidget',
  WidgetDjTypes.SlideTransition: 'SlideTransition',
  WidgetDjTypes.ScaleTransition: 'ScaleTransition',
  WidgetDjTypes.RotationTransition: 'RotationTransition',
  WidgetDjTypes.SizeTransition: 'SizeTransition',
  WidgetDjTypes.FadeTransition: 'FadeTransition',
  WidgetDjTypes.SliverFadeTransition: 'SliverFadeTransition',
  WidgetDjTypes.RelativeRectTween: 'RelativeRectTween',
  WidgetDjTypes.PositionedTransition: 'PositionedTransition',
  WidgetDjTypes.RelativePositionedTransition: 'RelativePositionedTransition',
  WidgetDjTypes.DecoratedBoxTransition: 'DecoratedBoxTransition',
  WidgetDjTypes.AlignTransition: 'AlignTransition',
  WidgetDjTypes.DefaultTextStyleTransition: 'DefaultTextStyleTransition',
  WidgetDjTypes.AnimatedBuilder: 'AnimatedBuilder',
  WidgetDjTypes.TweenAnimationBuilder: 'TweenAnimationBuilder',
  WidgetDjTypes.UniqueWidget: 'UniqueWidget',
  WidgetDjTypes.ValueListenableBuilder: 'ValueListenableBuilder',
  WidgetDjTypes.Viewport: 'Viewport',
  WidgetDjTypes.ShrinkWrappingViewport: 'ShrinkWrappingViewport',
  WidgetDjTypes.Visibility: 'Visibility',
  WidgetDjTypes.SliverVisibility: 'SliverVisibility',
  WidgetDjTypes.WidgetInspector: 'WidgetInspector',
  WidgetDjTypes.InspectorSelection: 'InspectorSelection',
  WidgetDjTypes.DevToolsDeepLinkProperty: 'DevToolsDeepLinkProperty',
  WidgetDjTypes.InspectorSerializationDelegate:
      'InspectorSerializationDelegate',
  WidgetDjTypes.WidgetSpan: 'WidgetSpan',
  WidgetDjTypes.WillPopScope: 'WillPopScope',
};
